--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorType(1)
panel:setBackGroundColor({r = 150, g = 200, b = 255})
panel:setBackGroundColorOpacity(90)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(5)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
Node:addChild(panel)

--Create img_bg
local img_bg = ccui.ImageView:create()
img_bg:ignoreContentAdaptWithSize(false)
img_bg:loadTexture("common/layerbg/com_bg_pic_1.png",0)
img_bg:setScale9Enabled(true)
img_bg:setCapInsets({x = 145, y = 103, width = 1, height = 1})
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(3)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setSize({width = 1150.0000, height = 658.0000})
layout:setLeftMargin(-575.0000)
layout:setRightMargin(-575.0000)
layout:setTopMargin(-329.0000)
layout:setBottomMargin(-329.0000)
panel:addChild(img_bg)

--Create img_bg_2
local img_bg_2 = ccui.ImageView:create()
img_bg_2:ignoreContentAdaptWithSize(false)
img_bg_2:loadTexture("common/layerbg/com_bg_pic_bsbg.png",0)
img_bg_2:setScale9Enabled(true)
img_bg_2:setCapInsets({x = 37, y = 14, width = 1, height = 2})
img_bg_2:setLayoutComponentEnabled(true)
img_bg_2:setName("img_bg_2")
img_bg_2:setTag(4)
img_bg_2:setCascadeColorEnabled(true)
img_bg_2:setCascadeOpacityEnabled(true)
img_bg_2:setPosition(575.0000, 305.1267)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg_2)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4637)
layout:setPercentWidth(0.9687)
layout:setPercentHeight(0.8754)
layout:setSize({width = 1114.0000, height = 576.0000})
layout:setLeftMargin(18.0000)
layout:setRightMargin(18.0000)
layout:setTopMargin(64.8733)
layout:setBottomMargin(17.1267)
img_bg:addChild(img_bg_2)

--Create spr_title
local spr_title = cc.Sprite:create("hall/mail/mail_pic_words_yx.png")
spr_title:setName("spr_title")
spr_title:setTag(6)
spr_title:setCascadeColorEnabled(true)
spr_title:setCascadeOpacityEnabled(true)
spr_title:setPosition(0.0000, 294.2958)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_title)
layout:setSize({width = 98.0000, height = 46.0000})
layout:setLeftMargin(-49.0000)
layout:setRightMargin(-49.0000)
layout:setTopMargin(-317.2958)
layout:setBottomMargin(271.2958)
spr_title:setBlendFunc({src = 1, dst = 771})
panel:addChild(spr_title)

--Create btn_close
local btn_close = ccui.Button:create()
btn_close:ignoreContentAdaptWithSize(false)
btn_close:loadTextureNormal("common/btn/com_btn_close_0.png",0)
btn_close:loadTexturePressed("common/btn/com_btn_close_1.png",0)
btn_close:loadTextureDisabled("common/btn/com_btn_close_1.png",0)
btn_close:setTitleFontSize(14)
btn_close:setTitleColor({r = 65, g = 65, b = 70})
btn_close:setScale9Enabled(true)
btn_close:setCapInsets({x = 15, y = 11, width = 40, height = 48})
btn_close:setLayoutComponentEnabled(true)
btn_close:setName("btn_close")
btn_close:setTag(89)
btn_close:setCascadeColorEnabled(true)
btn_close:setCascadeOpacityEnabled(true)
btn_close:setPosition(553.4095, 302.0874)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_close)
layout:setSize({width = 70.0000, height = 70.0000})
layout:setLeftMargin(518.4095)
layout:setRightMargin(-588.4095)
layout:setTopMargin(-337.0874)
layout:setBottomMargin(267.0874)
panel:addChild(btn_close)

--Create scroll_list
local scroll_list = ccui.ScrollView:create()
scroll_list:setBounceEnabled(true)
scroll_list:setInnerContainerSize({width = 1048, height = 538})
scroll_list:ignoreContentAdaptWithSize(false)
scroll_list:setBackGroundImage("common/layerbg/com_boxs_bg.png",0)
scroll_list:setClippingEnabled(true)
scroll_list:setBackGroundImageCapInsets({x = 14, y = 14, width = 16, height = 16})
scroll_list:setBackGroundColorType(1)
scroll_list:setBackGroundColor({r = 255, g = 150, b = 100})
scroll_list:setBackGroundColorOpacity(0)
scroll_list:setBackGroundImageScale9Enabled(true)
scroll_list:setLayoutComponentEnabled(true)
scroll_list:setName("scroll_list")
scroll_list:setTag(90)
scroll_list:setCascadeColorEnabled(true)
scroll_list:setCascadeOpacityEnabled(true)
scroll_list:setAnchorPoint(0.5000, 0.5000)
scroll_list:setPosition(0.0001, 4.9520)
layout = ccui.LayoutComponent:bindLayoutComponent(scroll_list)
layout:setSize({width = 1048.0000, height = 500.0000})
layout:setLeftMargin(-523.9999)
layout:setRightMargin(-524.0001)
layout:setTopMargin(-254.9520)
layout:setBottomMargin(-245.0480)
panel:addChild(scroll_list)

--Create img_down
local img_down = ccui.ImageView:create()
img_down:ignoreContentAdaptWithSize(false)
img_down:loadTexture("common/com_boxs_shadow.png",0)
img_down:setScale9Enabled(true)
img_down:setCapInsets({x = 20, y = 2, width = 1, height = 4})
img_down:setLayoutComponentEnabled(true)
img_down:setName("img_down")
img_down:setTag(409)
img_down:setCascadeColorEnabled(true)
img_down:setCascadeOpacityEnabled(true)
img_down:setPosition(0.0000, -241.2543)
layout = ccui.LayoutComponent:bindLayoutComponent(img_down)
layout:setPositionPercentXEnabled(true)
layout:setSize({width = 1048.0000, height = 8.0000})
layout:setLeftMargin(-524.0000)
layout:setRightMargin(-524.0000)
layout:setTopMargin(237.2543)
layout:setBottomMargin(-245.2543)
panel:addChild(img_down)

--Create img_top
local img_top = ccui.ImageView:create()
img_top:ignoreContentAdaptWithSize(false)
img_top:loadTexture("common/com_boxs_shadow.png",0)
img_top:setScale9Enabled(true)
img_top:setCapInsets({x = 20, y = 2, width = 1, height = 4})
img_top:setLayoutComponentEnabled(true)
img_top:setName("img_top")
img_top:setTag(410)
img_top:setCascadeColorEnabled(true)
img_top:setCascadeOpacityEnabled(true)
img_top:setPosition(0.0000, 250.7099)
img_top:setRotationSkewX(180.0000)
img_top:setRotationSkewY(180.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_top)
layout:setPositionPercentXEnabled(true)
layout:setSize({width = 1048.0000, height = 8.0000})
layout:setLeftMargin(-524.0000)
layout:setRightMargin(-524.0000)
layout:setTopMargin(-254.7099)
layout:setBottomMargin(246.7099)
panel:addChild(img_top)

--Create text_notice
local text_notice = ccui.Text:create()
text_notice:ignoreContentAdaptWithSize(true)
text_notice:setTextAreaSize({width = 0, height = 0})
text_notice:setFontSize(20)
text_notice:setString([[提示：邮件在]])
text_notice:setLayoutComponentEnabled(true)
text_notice:setName("text_notice")
text_notice:setTag(33)
text_notice:setCascadeColorEnabled(true)
text_notice:setCascadeOpacityEnabled(true)
text_notice:setPosition(0.0000, -276.8863)
text_notice:setTextColor({r = 232, g = 107, b = 105})
layout = ccui.LayoutComponent:bindLayoutComponent(text_notice)
layout:setPositionPercentXEnabled(true)
layout:setSize({width = 120.0000, height = 20.0000})
layout:setLeftMargin(-60.0000)
layout:setRightMargin(-60.0000)
layout:setTopMargin(266.8863)
layout:setBottomMargin(-286.8863)
panel:addChild(text_notice)

--Create spr_words_nomail
local spr_words_nomail = cc.Sprite:create("hall/mail/mail_pic_words_myxyj.png")
spr_words_nomail:setName("spr_words_nomail")
spr_words_nomail:setTag(348)
spr_words_nomail:setCascadeColorEnabled(true)
spr_words_nomail:setCascadeOpacityEnabled(true)
spr_words_nomail:setPosition(0.0000, 5.9999)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_words_nomail)
layout:setPositionPercentXEnabled(true)
layout:setSize({width = 184.0000, height = 42.0000})
layout:setLeftMargin(-92.0000)
layout:setRightMargin(-92.0000)
layout:setTopMargin(-26.9999)
layout:setBottomMargin(-15.0001)
spr_words_nomail:setBlendFunc({src = 1, dst = 771})
panel:addChild(spr_words_nomail)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

