--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorType(1)
panel:setBackGroundColor({r = 150, g = 200, b = 255})
panel:setBackGroundColorOpacity(102)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(129)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
Node:addChild(panel)

--Create image_bg
local image_bg = ccui.ImageView:create()
image_bg:ignoreContentAdaptWithSize(false)
image_bg:loadTexture("common/layerbg/com_bg_pic_3.png",0)
image_bg:setScale9Enabled(true)
image_bg:setCapInsets({x = 100, y = 76, width = 90, height = 32})
image_bg:setLayoutComponentEnabled(true)
image_bg:setName("image_bg")
image_bg:setTag(130)
image_bg:setCascadeColorEnabled(true)
image_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(image_bg)
layout:setSize({width = 700.0000, height = 456.0000})
layout:setLeftMargin(-350.0000)
layout:setRightMargin(-350.0000)
layout:setTopMargin(-228.0000)
layout:setBottomMargin(-228.0000)
panel:addChild(image_bg)

--Create img_bg_1
local img_bg_1 = ccui.ImageView:create()
img_bg_1:ignoreContentAdaptWithSize(false)
img_bg_1:loadTexture("common/layerbg/com_bg_pic_bsbg.png",0)
img_bg_1:setScale9Enabled(true)
img_bg_1:setCapInsets({x = 36, y = 5, width = 2, height = 1})
img_bg_1:setLayoutComponentEnabled(true)
img_bg_1:setName("img_bg_1")
img_bg_1:setTag(319)
img_bg_1:setCascadeColorEnabled(true)
img_bg_1:setCascadeOpacityEnabled(true)
img_bg_1:setPosition(350.0000, 201.4305)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4417)
layout:setPercentWidth(0.9514)
layout:setPercentHeight(0.8114)
layout:setSize({width = 666.0000, height = 370.0000})
layout:setLeftMargin(17.0000)
layout:setRightMargin(17.0000)
layout:setTopMargin(69.5695)
layout:setBottomMargin(16.4305)
image_bg:addChild(img_bg_1)

--Create spr_title
local spr_title = cc.Sprite:create("hall/friend/fr_pic_title_cjcg.png")
spr_title:setName("spr_title")
spr_title:setTag(131)
spr_title:setCascadeColorEnabled(true)
spr_title:setCascadeOpacityEnabled(true)
spr_title:setPosition(0.0000, 185.2776)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_title)
layout:setPositionPercentXEnabled(true)
layout:setSize({width = 160.0000, height = 42.0000})
layout:setLeftMargin(-80.0000)
layout:setRightMargin(-80.0000)
layout:setTopMargin(-206.2776)
layout:setBottomMargin(164.2776)
spr_title:setBlendFunc({src = 1, dst = 771})
panel:addChild(spr_title)

--Create btn_share
local btn_share = ccui.Button:create()
btn_share:ignoreContentAdaptWithSize(false)
btn_share:loadTextureNormal("common/btn/com_btn_blue_0.png",0)
btn_share:loadTexturePressed("common/btn/com_btn_blue_1.png",0)
btn_share:loadTextureDisabled("common/btn/com_btn_blue_1.png",0)
btn_share:setTitleFontSize(14)
btn_share:setTitleColor({r = 65, g = 65, b = 70})
btn_share:setScale9Enabled(true)
btn_share:setCapInsets({x = 60, y = 40, width = 38, height = 2})
btn_share:setLayoutComponentEnabled(true)
btn_share:setName("btn_share")
btn_share:setTag(133)
btn_share:setCascadeColorEnabled(true)
btn_share:setCascadeOpacityEnabled(true)
btn_share:setPosition(-164.5800, -142.7042)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_share)
layout:setSize({width = 225.0000, height = 82.0000})
layout:setLeftMargin(-277.0800)
layout:setRightMargin(52.0800)
layout:setTopMargin(101.7042)
layout:setBottomMargin(-183.7042)
panel:addChild(btn_share)

--Create spr_qx
local spr_qx = cc.Sprite:create("hall/friend/fr_btn_hyfx.png")
spr_qx:setName("spr_qx")
spr_qx:setTag(134)
spr_qx:setCascadeColorEnabled(true)
spr_qx:setCascadeOpacityEnabled(true)
spr_qx:setPosition(112.0000, 46.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_qx)
layout:setPositionPercentX(0.4978)
layout:setPositionPercentY(0.5610)
layout:setPercentWidth(0.6844)
layout:setPercentHeight(0.5854)
layout:setSize({width = 154.0000, height = 48.0000})
layout:setLeftMargin(35.0000)
layout:setRightMargin(36.0000)
layout:setTopMargin(12.0000)
layout:setBottomMargin(22.0000)
spr_qx:setBlendFunc({src = 1, dst = 771})
btn_share:addChild(spr_qx)

--Create btn_enter
local btn_enter = ccui.Button:create()
btn_enter:ignoreContentAdaptWithSize(false)
btn_enter:loadTextureNormal("common/btn/com_btn_orange_0.png",0)
btn_enter:loadTexturePressed("common/btn/com_btn_orange_1.png",0)
btn_enter:loadTextureDisabled("common/btn/com_btn_orange_1.png",0)
btn_enter:setTitleFontSize(14)
btn_enter:setTitleColor({r = 65, g = 65, b = 70})
btn_enter:setScale9Enabled(true)
btn_enter:setCapInsets({x = 60, y = 40, width = 38, height = 2})
btn_enter:setLayoutComponentEnabled(true)
btn_enter:setName("btn_enter")
btn_enter:setTag(135)
btn_enter:setCascadeColorEnabled(true)
btn_enter:setCascadeOpacityEnabled(true)
btn_enter:setPosition(164.5800, -138.2100)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_enter)
layout:setSize({width = 225.0000, height = 82.0000})
layout:setLeftMargin(52.0800)
layout:setRightMargin(-277.0800)
layout:setTopMargin(97.2100)
layout:setBottomMargin(-179.2100)
panel:addChild(btn_enter)

--Create spr_jrfj
local spr_jrfj = cc.Sprite:create("hall/friend/fr_btn_jrfj.png")
spr_jrfj:setName("spr_jrfj")
spr_jrfj:setTag(136)
spr_jrfj:setCascadeColorEnabled(true)
spr_jrfj:setCascadeOpacityEnabled(true)
spr_jrfj:setPosition(112.0000, 46.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_jrfj)
layout:setPositionPercentX(0.4978)
layout:setPositionPercentY(0.5610)
layout:setPercentWidth(0.6844)
layout:setPercentHeight(0.5854)
layout:setSize({width = 154.0000, height = 48.0000})
layout:setLeftMargin(35.0000)
layout:setRightMargin(36.0000)
layout:setTopMargin(12.0000)
layout:setBottomMargin(22.0000)
spr_jrfj:setBlendFunc({src = 1, dst = 771})
btn_enter:addChild(spr_jrfj)

--Create text_notice_1
local text_notice_1 = ccui.Text:create()
text_notice_1:ignoreContentAdaptWithSize(true)
text_notice_1:setTextAreaSize({width = 0, height = 0})
text_notice_1:setFontSize(34)
text_notice_1:setString([[昵称只能设置一次]])
text_notice_1:setLayoutComponentEnabled(true)
text_notice_1:setName("text_notice_1")
text_notice_1:setTag(320)
text_notice_1:setCascadeColorEnabled(true)
text_notice_1:setCascadeOpacityEnabled(true)
text_notice_1:setPosition(0.0000, 116.9714)
text_notice_1:setTextColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(text_notice_1)
layout:setPositionPercentXEnabled(true)
layout:setSize({width = 272.0000, height = 34.0000})
layout:setLeftMargin(-136.0000)
layout:setRightMargin(-136.0000)
layout:setTopMargin(-133.9714)
layout:setBottomMargin(99.9714)
panel:addChild(text_notice_1)

--Create text_notice_2
local text_notice_2 = ccui.Text:create()
text_notice_2:ignoreContentAdaptWithSize(false)
text_notice_2:setFontSize(28)
text_notice_2:setString([[昵称只能设置一次，一旦确定不能再进行修改]])
text_notice_2:setLayoutComponentEnabled(true)
text_notice_2:setName("text_notice_2")
text_notice_2:setTag(728)
text_notice_2:setCascadeColorEnabled(true)
text_notice_2:setCascadeOpacityEnabled(true)
text_notice_2:setPosition(0.0000, -55.5930)
text_notice_2:setTextColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(text_notice_2)
layout:setPositionPercentXEnabled(true)
layout:setSize({width = 450.0000, height = 70.0000})
layout:setLeftMargin(-225.0000)
layout:setRightMargin(-225.0000)
layout:setTopMargin(20.5930)
layout:setBottomMargin(-90.5930)
panel:addChild(text_notice_2)

--Create image_bg
local image_bg = ccui.ImageView:create()
image_bg:ignoreContentAdaptWithSize(false)
image_bg:loadTexture("common/layerbg/com_pic_insert_bg.png",0)
image_bg:setScale9Enabled(true)
image_bg:setCapInsets({x = 18, y = 19, width = 6, height = 3})
image_bg:setLayoutComponentEnabled(true)
image_bg:setName("image_bg")
image_bg:setTag(727)
image_bg:setCascadeColorEnabled(true)
image_bg:setCascadeOpacityEnabled(true)
image_bg:setPosition(0.0000, 42.4668)
layout = ccui.LayoutComponent:bindLayoutComponent(image_bg)
layout:setPositionPercentXEnabled(true)
layout:setSize({width = 470.0000, height = 72.0000})
layout:setLeftMargin(-235.0000)
layout:setRightMargin(-235.0000)
layout:setTopMargin(-78.4668)
layout:setBottomMargin(6.4668)
panel:addChild(image_bg)

--Create text_roomno
local text_roomno = ccui.Text:create()
text_roomno:ignoreContentAdaptWithSize(true)
text_roomno:setTextAreaSize({width = 0, height = 0})
text_roomno:setFontSize(60)
text_roomno:setString([[888888]])
text_roomno:setTextHorizontalAlignment(1)
text_roomno:setTextVerticalAlignment(1)
text_roomno:setLayoutComponentEnabled(true)
text_roomno:setName("text_roomno")
text_roomno:setTag(729)
text_roomno:setCascadeColorEnabled(true)
text_roomno:setCascadeOpacityEnabled(true)
text_roomno:setPosition(235.0000, 36.0000)
text_roomno:setTextColor({r = 154, g = 10, b = 10})
layout = ccui.LayoutComponent:bindLayoutComponent(text_roomno)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3830)
layout:setPercentHeight(0.8333)
layout:setSize({width = 180.0000, height = 60.0000})
layout:setLeftMargin(145.0000)
layout:setRightMargin(145.0000)
layout:setTopMargin(6.0000)
layout:setBottomMargin(6.0000)
image_bg:addChild(text_roomno)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

