--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create img_bg
local img_bg = ccui.ImageView:create()
img_bg:ignoreContentAdaptWithSize(false)
img_bg:loadTexture("battle/friend/friend_bg_6.png",0)
img_bg:setScale9Enabled(true)
img_bg:setCapInsets({x = 0, y = 40, width = 8, height = 10})
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(27)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
img_bg:setAnchorPoint(0.0000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setPositionPercentYEnabled(true)
layout:setSize({width = 156.0000, height = 326.0000})
layout:setRightMargin(-156.0000)
layout:setTopMargin(-163.0000)
layout:setBottomMargin(-163.0000)
Node:addChild(img_bg)

--Create img_rank_my_bg
local img_rank_my_bg = ccui.ImageView:create()
img_rank_my_bg:ignoreContentAdaptWithSize(false)
img_rank_my_bg:loadTexture("battle/friend/friend_bg_3.png",0)
img_rank_my_bg:setScale9Enabled(true)
img_rank_my_bg:setCapInsets({x = -10, y = 1, width = 20, height = 8})
img_rank_my_bg:setLayoutComponentEnabled(true)
img_rank_my_bg:setName("img_rank_my_bg")
img_rank_my_bg:setTag(32)
img_rank_my_bg:setCascadeColorEnabled(true)
img_rank_my_bg:setCascadeOpacityEnabled(true)
img_rank_my_bg:setPosition(70.0000, 170.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_rank_my_bg)
layout:setPositionPercentX(0.4487)
layout:setPositionPercentY(0.5215)
layout:setPercentWidth(0.9615)
layout:setPercentHeight(0.1227)
layout:setSize({width = 150.0000, height = 40.0000})
layout:setLeftMargin(-5.0000)
layout:setRightMargin(11.0000)
layout:setTopMargin(136.0000)
layout:setBottomMargin(150.0000)
img_bg:addChild(img_rank_my_bg)

--Create node_rank_1
innerCSD = require("ui.battle.friend.uifriendrankitem")
innerProject = innerCSD.create(callBackProvider)
local node_rank_1 = innerProject.root
node_rank_1.animation = innerProject.animation
node_rank_1:setName("node_rank_1")
node_rank_1:setTag(233)
node_rank_1:setCascadeColorEnabled(true)
node_rank_1:setCascadeOpacityEnabled(true)
node_rank_1:setPosition(70.0000, 170.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_rank_1)
layout:setPositionPercentX(0.4487)
layout:setPositionPercentY(0.5215)
layout:setLeftMargin(70.0000)
layout:setRightMargin(86.0000)
layout:setTopMargin(156.0000)
layout:setBottomMargin(170.0000)
innerProject.animation:setTimeSpeed(1.0000)
node_rank_1:runAction(innerProject.animation)
img_bg:addChild(node_rank_1)

--Create node_rank_2
innerCSD = require("ui.battle.friend.uifriendrankitem")
innerProject = innerCSD.create(callBackProvider)
local node_rank_2 = innerProject.root
node_rank_2.animation = innerProject.animation
node_rank_2:setName("node_rank_2")
node_rank_2:setTag(238)
node_rank_2:setCascadeColorEnabled(true)
node_rank_2:setCascadeOpacityEnabled(true)
node_rank_2:setPosition(70.0000, 130.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_rank_2)
layout:setPositionPercentX(0.4487)
layout:setPositionPercentY(0.3988)
layout:setLeftMargin(70.0000)
layout:setRightMargin(86.0000)
layout:setTopMargin(196.0000)
layout:setBottomMargin(130.0000)
innerProject.animation:setTimeSpeed(1.0000)
node_rank_2:runAction(innerProject.animation)
img_bg:addChild(node_rank_2)

--Create node_rank_3
innerCSD = require("ui.battle.friend.uifriendrankitem")
innerProject = innerCSD.create(callBackProvider)
local node_rank_3 = innerProject.root
node_rank_3.animation = innerProject.animation
node_rank_3:setName("node_rank_3")
node_rank_3:setTag(243)
node_rank_3:setCascadeColorEnabled(true)
node_rank_3:setCascadeOpacityEnabled(true)
node_rank_3:setPosition(70.0000, 90.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_rank_3)
layout:setPositionPercentX(0.4487)
layout:setPositionPercentY(0.2761)
layout:setLeftMargin(70.0000)
layout:setRightMargin(86.0000)
layout:setTopMargin(236.0000)
layout:setBottomMargin(90.0000)
innerProject.animation:setTimeSpeed(1.0000)
node_rank_3:runAction(innerProject.animation)
img_bg:addChild(node_rank_3)

--Create node_rank_4
innerCSD = require("ui.battle.friend.uifriendrankitem")
innerProject = innerCSD.create(callBackProvider)
local node_rank_4 = innerProject.root
node_rank_4.animation = innerProject.animation
node_rank_4:setName("node_rank_4")
node_rank_4:setTag(248)
node_rank_4:setCascadeColorEnabled(true)
node_rank_4:setCascadeOpacityEnabled(true)
node_rank_4:setPosition(70.0000, 50.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_rank_4)
layout:setPositionPercentX(0.4487)
layout:setPositionPercentY(0.1534)
layout:setLeftMargin(70.0000)
layout:setRightMargin(86.0000)
layout:setTopMargin(276.0000)
layout:setBottomMargin(50.0000)
innerProject.animation:setTimeSpeed(1.0000)
node_rank_4:runAction(innerProject.animation)
img_bg:addChild(node_rank_4)

--Create spr_rank
local spr_rank = cc.Sprite:create("battle/friend/friend_text_pm.png")
spr_rank:setName("spr_rank")
spr_rank:setTag(136)
spr_rank:setCascadeColorEnabled(true)
spr_rank:setCascadeOpacityEnabled(true)
spr_rank:setPosition(28.0000, 45.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_rank)
layout:setSize({width = 36.0000, height = 18.0000})
layout:setLeftMargin(10.0000)
layout:setRightMargin(-46.0000)
layout:setTopMargin(-54.0000)
layout:setBottomMargin(36.0000)
spr_rank:setBlendFunc({src = 1, dst = 771})
Node:addChild(spr_rank)

--Create spr_amount
local spr_amount = cc.Sprite:create("battle/friend/friend_text_jf.png")
spr_amount:setName("spr_amount")
spr_amount:setTag(137)
spr_amount:setCascadeColorEnabled(true)
spr_amount:setCascadeOpacityEnabled(true)
spr_amount:setPosition(95.0000, 45.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_amount)
layout:setSize({width = 36.0000, height = 18.0000})
layout:setLeftMargin(77.0000)
layout:setRightMargin(-113.0000)
layout:setTopMargin(-54.0000)
layout:setBottomMargin(36.0000)
spr_amount:setBlendFunc({src = 1, dst = 771})
Node:addChild(spr_amount)

--Create spr_light_split
local spr_light_split = cc.Sprite:create("battle/friend/friend_light_6.png")
spr_light_split:setName("spr_light_split")
spr_light_split:setTag(138)
spr_light_split:setCascadeColorEnabled(true)
spr_light_split:setCascadeOpacityEnabled(true)
spr_light_split:setPosition(71.4489, 65.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_light_split)
layout:setSize({width = 148.0000, height = 2.0000})
layout:setLeftMargin(-2.5511)
layout:setRightMargin(-145.4489)
layout:setTopMargin(-66.0000)
layout:setBottomMargin(64.0000)
spr_light_split:setBlendFunc({src = 1, dst = 771})
Node:addChild(spr_light_split)

--Create spr_bswks
local spr_bswks = cc.Sprite:create("battle/friend/friend_text_bswks.png")
spr_bswks:setName("spr_bswks")
spr_bswks:setTag(144)
spr_bswks:setCascadeColorEnabled(true)
spr_bswks:setCascadeOpacityEnabled(true)
spr_bswks:setPosition(72.0000, 110.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_bswks)
layout:setSize({width = 130.0000, height = 28.0000})
layout:setLeftMargin(7.0000)
layout:setRightMargin(-137.0000)
layout:setTopMargin(-124.0000)
layout:setBottomMargin(96.0000)
spr_bswks:setBlendFunc({src = 1, dst = 771})
Node:addChild(spr_bswks)

--Create node_game_timeout
local node_game_timeout=cc.Node:create()
node_game_timeout:setName("node_game_timeout")
node_game_timeout:setTag(132)
node_game_timeout:setCascadeColorEnabled(true)
node_game_timeout:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(node_game_timeout)
Node:addChild(node_game_timeout)

--Create spr_bsdjs
local spr_bsdjs = cc.Sprite:create("battle/friend/friend_text_bsdjs.png")
spr_bsdjs:setName("spr_bsdjs")
spr_bsdjs:setTag(139)
spr_bsdjs:setCascadeColorEnabled(true)
spr_bsdjs:setCascadeOpacityEnabled(true)
spr_bsdjs:setPosition(72.4564, 125.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_bsdjs)
layout:setSize({width = 92.0000, height = 18.0000})
layout:setLeftMargin(26.4564)
layout:setRightMargin(-118.4564)
layout:setTopMargin(-134.0000)
layout:setBottomMargin(116.0000)
spr_bsdjs:setBlendFunc({src = 1, dst = 771})
node_game_timeout:addChild(spr_bsdjs)

--Create fnt_time_minu
local fnt_time_minu = ccui.TextBMFont:create()
fnt_time_minu:setFntFile("fnt/fr_num.fnt")
fnt_time_minu:setString([[00]])
fnt_time_minu:setLayoutComponentEnabled(true)
fnt_time_minu:setName("fnt_time_minu")
fnt_time_minu:setTag(141)
fnt_time_minu:setCascadeColorEnabled(true)
fnt_time_minu:setCascadeOpacityEnabled(true)
fnt_time_minu:setPosition(45.0000, 90.0000)
fnt_time_minu:setScaleX(0.8000)
fnt_time_minu:setScaleY(0.8000)
fnt_time_minu:setColor({r = 251, g = 154, b = 154})
layout = ccui.LayoutComponent:bindLayoutComponent(fnt_time_minu)
layout:setSize({width = 44.0000, height = 36.0000})
layout:setLeftMargin(23.0000)
layout:setRightMargin(-67.0000)
layout:setTopMargin(-108.0000)
layout:setBottomMargin(72.0000)
node_game_timeout:addChild(fnt_time_minu)

--Create fnt_time_sec
local fnt_time_sec = ccui.TextBMFont:create()
fnt_time_sec:setFntFile("fnt/fr_num.fnt")
fnt_time_sec:setString([[00]])
fnt_time_sec:setLayoutComponentEnabled(true)
fnt_time_sec:setName("fnt_time_sec")
fnt_time_sec:setTag(140)
fnt_time_sec:setCascadeColorEnabled(true)
fnt_time_sec:setCascadeOpacityEnabled(true)
fnt_time_sec:setPosition(97.0000, 90.0000)
fnt_time_sec:setScaleX(0.8000)
fnt_time_sec:setScaleY(0.8000)
fnt_time_sec:setColor({r = 251, g = 154, b = 154})
layout = ccui.LayoutComponent:bindLayoutComponent(fnt_time_sec)
layout:setSize({width = 44.0000, height = 36.0000})
layout:setLeftMargin(75.0000)
layout:setRightMargin(-119.0000)
layout:setTopMargin(-108.0000)
layout:setBottomMargin(72.0000)
node_game_timeout:addChild(fnt_time_sec)

--Create text_point_1
local text_point_1 = ccui.TextBMFont:create()
text_point_1:setFntFile("fnt/fr_num.fnt")
text_point_1:setString([[.]])
text_point_1:setLayoutComponentEnabled(true)
text_point_1:setName("text_point_1")
text_point_1:setTag(142)
text_point_1:setCascadeColorEnabled(true)
text_point_1:setCascadeOpacityEnabled(true)
text_point_1:setPosition(73.0000, 94.0000)
text_point_1:setScaleX(0.8000)
text_point_1:setScaleY(0.8000)
text_point_1:setColor({r = 251, g = 154, b = 154})
layout = ccui.LayoutComponent:bindLayoutComponent(text_point_1)
layout:setSize({width = 22.0000, height = 36.0000})
layout:setLeftMargin(62.0000)
layout:setRightMargin(-84.0000)
layout:setTopMargin(-112.0000)
layout:setBottomMargin(76.0000)
node_game_timeout:addChild(text_point_1)

--Create text_point_2
local text_point_2 = ccui.TextBMFont:create()
text_point_2:setFntFile("fnt/fr_num.fnt")
text_point_2:setString([[.]])
text_point_2:setLayoutComponentEnabled(true)
text_point_2:setName("text_point_2")
text_point_2:setTag(143)
text_point_2:setCascadeColorEnabled(true)
text_point_2:setCascadeOpacityEnabled(true)
text_point_2:setPosition(73.0000, 102.0000)
text_point_2:setScaleX(0.8000)
text_point_2:setScaleY(0.8000)
text_point_2:setColor({r = 251, g = 154, b = 154})
layout = ccui.LayoutComponent:bindLayoutComponent(text_point_2)
layout:setSize({width = 22.0000, height = 36.0000})
layout:setLeftMargin(62.0000)
layout:setRightMargin(-84.0000)
layout:setTopMargin(-120.0000)
layout:setBottomMargin(84.0000)
node_game_timeout:addChild(text_point_2)

--Create effect_fr_line_1
local effect_fr_line_1 = cc.Sprite:create("common/com_effect_light.png")
effect_fr_line_1:setName("effect_fr_line_1")
effect_fr_line_1:setTag(109)
effect_fr_line_1:setCascadeColorEnabled(true)
effect_fr_line_1:setCascadeOpacityEnabled(true)
effect_fr_line_1:setPosition(72.4987, 88.0286)
effect_fr_line_1:setScaleX(3.9000)
effect_fr_line_1:setScaleY(1.3658)
effect_fr_line_1:setOpacity(0)
effect_fr_line_1:setColor({r = 255, g = 86, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(effect_fr_line_1)
layout:setSize({width = 66.0000, height = 66.0000})
layout:setLeftMargin(39.4987)
layout:setRightMargin(-105.4987)
layout:setTopMargin(-121.0286)
layout:setBottomMargin(55.0286)
effect_fr_line_1:setBlendFunc({src = 770, dst = 1})
node_game_timeout:addChild(effect_fr_line_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(61)
result['animation']:setTimeSpeed(1.0000)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(72.4987)
localFrame:setY(88.0286)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(1)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(72.4987)
localFrame:setY(88.0286)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(31)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(72.4987)
localFrame:setY(88.0286)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(61)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(72.4987)
localFrame:setY(88.0286)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(effect_fr_line_1)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(3.9000)
localFrame:setScaleY(1.3658)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(1)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(3.9000)
localFrame:setScaleY(1.3658)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(31)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(4.5000)
localFrame:setScaleY(2.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(61)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(3.9000)
localFrame:setScaleY(1.3596)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(effect_fr_line_1)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(1)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(31)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(61)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(effect_fr_line_1)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(1)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(31)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(61)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(effect_fr_line_1)
--Create Animation List
local effect_light = {name="effect_light", startIndex=1, endIndex=61}
result['animation']:addAnimationInfo(effect_light)
local init = {name="init", startIndex=0, endIndex=1}
result['animation']:addAnimationInfo(init)

result['root'] = Node
return result;
end

return Result

