--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create node_bottom
local node_bottom=cc.Node:create()
node_bottom:setName("node_bottom")
node_bottom:setTag(5459)
node_bottom:setCascadeColorEnabled(true)
node_bottom:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(node_bottom)
Node:addChild(node_bottom)

--Create spr_circle
local spr_circle = cc.Sprite:create("battle/cannon/bl_pic_player_circle.png")
spr_circle:setName("spr_circle")
spr_circle:setTag(61)
spr_circle:setCascadeColorEnabled(true)
spr_circle:setCascadeOpacityEnabled(true)
spr_circle:setPosition(0.0000, 26.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_circle)
layout:setSize({width = 198.0000, height = 198.0000})
layout:setLeftMargin(-99.0000)
layout:setRightMargin(-99.0000)
layout:setTopMargin(-125.0000)
layout:setBottomMargin(-73.0000)
spr_circle:setBlendFunc({src = 1, dst = 771})
Node:addChild(spr_circle)

--Create spr_cannon_base
local spr_cannon_base = cc.Sprite:create("battle/cannon/bl_cannon_base_01.png")
spr_cannon_base:setName("spr_cannon_base")
spr_cannon_base:setTag(6)
spr_cannon_base:setCascadeColorEnabled(true)
spr_cannon_base:setCascadeOpacityEnabled(true)
spr_cannon_base:setPosition(0.0001, 40.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_cannon_base)
layout:setSize({width = 192.0000, height = 80.0000})
layout:setLeftMargin(-95.9999)
layout:setRightMargin(-96.0001)
layout:setTopMargin(-80.0000)
spr_cannon_base:setBlendFunc({src = 1, dst = 771})
Node:addChild(spr_cannon_base)

--Create node_gun
local node_gun=cc.Node:create()
node_gun:setName("node_gun")
node_gun:setTag(18)
node_gun:setCascadeColorEnabled(true)
node_gun:setCascadeOpacityEnabled(true)
node_gun:setPosition(0.0000, 38.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_gun)
layout:setTopMargin(-38.0000)
layout:setBottomMargin(38.0000)
Node:addChild(node_gun)

--Create spr_gunfire
local spr_gunfire = cc.Sprite:create("battle/effect/gunfire_1_00.png")
spr_gunfire:setName("spr_gunfire")
spr_gunfire:setTag(16)
spr_gunfire:setCascadeColorEnabled(true)
spr_gunfire:setCascadeOpacityEnabled(true)
spr_gunfire:setAnchorPoint(0.5000, 0.3300)
spr_gunfire:setPosition(-0.4123, 115.3675)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_gunfire)
layout:setSize({width = 128.0000, height = 160.0000})
layout:setLeftMargin(-64.4123)
layout:setRightMargin(-63.5877)
layout:setTopMargin(-222.5675)
layout:setBottomMargin(62.5675)
spr_gunfire:setBlendFunc({src = 1, dst = 771})
node_gun:addChild(spr_gunfire)

--Create spr_cannon
local spr_cannon = cc.Sprite:create("battle/cannon/bl_gun_01.png")
spr_cannon:setName("spr_cannon")
spr_cannon:setTag(5)
spr_cannon:setCascadeColorEnabled(true)
spr_cannon:setCascadeOpacityEnabled(true)
spr_cannon:setAnchorPoint(0.5000, 0.0000)
spr_cannon:setPosition(-0.4109, -28.6700)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_cannon)
layout:setSize({width = 140.0000, height = 144.0000})
layout:setLeftMargin(-70.4109)
layout:setRightMargin(-69.5891)
layout:setTopMargin(-115.3300)
layout:setBottomMargin(-28.6700)
spr_cannon:setBlendFunc({src = 1, dst = 771})
node_gun:addChild(spr_cannon)

--Create spr_multiple_bg
local spr_multiple_bg = cc.Sprite:create("battle/cannon/bl_multiple_bg.png")
spr_multiple_bg:setName("spr_multiple_bg")
spr_multiple_bg:setTag(7)
spr_multiple_bg:setCascadeColorEnabled(true)
spr_multiple_bg:setCascadeOpacityEnabled(true)
spr_multiple_bg:setAnchorPoint(0.5000, 0.0000)
spr_multiple_bg:setPosition(0.0000, -1.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_multiple_bg)
layout:setSize({width = 140.0000, height = 40.0000})
layout:setLeftMargin(-70.0000)
layout:setRightMargin(-70.0000)
layout:setTopMargin(-39.0000)
layout:setBottomMargin(-1.0000)
spr_multiple_bg:setBlendFunc({src = 1, dst = 771})
Node:addChild(spr_multiple_bg)

--Create node_touch
local node_touch=cc.Node:create()
node_touch:setName("node_touch")
node_touch:setTag(96)
node_touch:setCascadeColorEnabled(true)
node_touch:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(node_touch)
Node:addChild(node_touch)

--Create panel_1
local panel_1 = ccui.Layout:create()
panel_1:ignoreContentAdaptWithSize(false)
panel_1:setClippingEnabled(false)
panel_1:setBackGroundColorType(1)
panel_1:setBackGroundColor({r = 150, g = 200, b = 255})
panel_1:setBackGroundColorOpacity(0)
panel_1:setLayoutComponentEnabled(true)
panel_1:setName("panel_1")
panel_1:setTag(95)
panel_1:setCascadeColorEnabled(true)
panel_1:setCascadeOpacityEnabled(true)
panel_1:setAnchorPoint(0.5000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel_1)
layout:setSize({width = 250.0000, height = 150.0000})
layout:setLeftMargin(-125.0000)
layout:setRightMargin(-125.0000)
layout:setTopMargin(-150.0000)
node_touch:addChild(panel_1)

--Create fnt_multiple
local fnt_multiple = ccui.TextBMFont:create()
fnt_multiple:setFntFile("fnt/multiple_num.fnt")
fnt_multiple:setString([[88888]])
fnt_multiple:setLayoutComponentEnabled(true)
fnt_multiple:setName("fnt_multiple")
fnt_multiple:setTag(43)
fnt_multiple:setCascadeColorEnabled(true)
fnt_multiple:setCascadeOpacityEnabled(true)
fnt_multiple:setPosition(0.0000, 20.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(fnt_multiple)
layout:setSize({width = 110.0000, height = 22.0000})
layout:setLeftMargin(-55.0000)
layout:setRightMargin(-55.0000)
layout:setTopMargin(-31.0000)
layout:setBottomMargin(9.0000)
Node:addChild(fnt_multiple)

--Create spr_gun_lock
local spr_gun_lock = cc.Sprite:create("battle/cannon/bl_gun_lock.png")
spr_gun_lock:setName("spr_gun_lock")
spr_gun_lock:setTag(67)
spr_gun_lock:setCascadeColorEnabled(true)
spr_gun_lock:setCascadeOpacityEnabled(true)
spr_gun_lock:setPosition(0.0000, 72.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_gun_lock)
layout:setSize({width = 74.0000, height = 74.0000})
layout:setLeftMargin(-37.0000)
layout:setRightMargin(-37.0000)
layout:setTopMargin(-109.0000)
layout:setBottomMargin(35.0000)
spr_gun_lock:setBlendFunc({src = 1, dst = 771})
Node:addChild(spr_gun_lock)

--Create spr_light
local spr_light = cc.Sprite:create("common/com_changecannon.png")
spr_light:setName("spr_light")
spr_light:setTag(426)
spr_light:setCascadeColorEnabled(true)
spr_light:setCascadeOpacityEnabled(true)
spr_light:setPosition(0.0000, 87.6399)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_light)
layout:setPositionPercentXEnabled(true)
layout:setSize({width = 144.0000, height = 148.0000})
layout:setLeftMargin(-72.0000)
layout:setRightMargin(-72.0000)
layout:setTopMargin(-161.6399)
layout:setBottomMargin(13.6399)
spr_light:setBlendFunc({src = 1, dst = 771})
Node:addChild(spr_light)

--Create node_top
local node_top=cc.Node:create()
node_top:setName("node_top")
node_top:setTag(5460)
node_top:setCascadeColorEnabled(true)
node_top:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(node_top)
Node:addChild(node_top)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(200)
result['animation']:setTimeSpeed(1.0000)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(26.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(200)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(43.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(spr_circle)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(200)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(spr_circle)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(200)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(360.0000)
localFrame:setSkewY(360.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(spr_circle)
--Create Animation List

result['root'] = Node
return result;
end

return Result

