--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorType(1)
panel:setBackGroundColor({r = 0, g = 0, b = 0})
panel:setBackGroundColorOpacity(0)
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(143)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setPosition(-0.0001, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setLeftMargin(-0.0001)
layout:setRightMargin(0.0001)
Node:addChild(panel)

--Create node_1
local node_1=cc.Node:create()
node_1:setName("node_1")
node_1:setTag(935)
node_1:setCascadeColorEnabled(true)
node_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(node_1)
panel:addChild(node_1)

--Create btn_player_info_1
local btn_player_info_1 = ccui.Button:create()
btn_player_info_1:ignoreContentAdaptWithSize(false)
btn_player_info_1:loadTextureNormal("common/btn/com_btn_green3_0.png",0)
btn_player_info_1:loadTexturePressed("common/btn/com_btn_green3_0.png",0)
btn_player_info_1:loadTextureDisabled("common/btn/com_btn_green3_0.png",0)
btn_player_info_1:setTitleFontSize(14)
btn_player_info_1:setTitleColor({r = 65, g = 65, b = 70})
btn_player_info_1:setLayoutComponentEnabled(true)
btn_player_info_1:setName("btn_player_info_1")
btn_player_info_1:setTag(144)
btn_player_info_1:setCascadeColorEnabled(true)
btn_player_info_1:setCascadeOpacityEnabled(true)
btn_player_info_1:setPosition(333.0000, 28.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_player_info_1)
layout:setSize({width = 126.0000, height = 64.0000})
layout:setLeftMargin(270.0000)
layout:setRightMargin(-396.0000)
layout:setTopMargin(-60.0000)
layout:setBottomMargin(-4.0000)
node_1:addChild(btn_player_info_1)

--Create spr_check_info
local spr_check_info = cc.Sprite:create("hall/friend/fr_btn_ck.png")
spr_check_info:setName("spr_check_info")
spr_check_info:setTag(145)
spr_check_info:setCascadeColorEnabled(true)
spr_check_info:setCascadeOpacityEnabled(true)
spr_check_info:setPosition(63.0000, 35.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_check_info)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5469)
layout:setPercentWidth(0.6190)
layout:setPercentHeight(0.6563)
layout:setSize({width = 78.0000, height = 42.0000})
layout:setLeftMargin(24.0000)
layout:setRightMargin(24.0000)
layout:setTopMargin(8.0000)
layout:setBottomMargin(14.0000)
spr_check_info:setBlendFunc({src = 1, dst = 771})
btn_player_info_1:addChild(spr_check_info)

--Create node_player_info_1
innerCSD = require("ui.playerinfo.uigameplayerinfo")
innerProject = innerCSD.create(callBackProvider)
local node_player_info_1 = innerProject.root
node_player_info_1.animation = innerProject.animation
node_player_info_1:setName("node_player_info_1")
node_player_info_1:setTag(152)
node_player_info_1:setCascadeColorEnabled(true)
node_player_info_1:setCascadeOpacityEnabled(true)
node_player_info_1:setPosition(333.0005, 357.0013)
layout = ccui.LayoutComponent:bindLayoutComponent(node_player_info_1)
layout:setLeftMargin(333.0005)
layout:setRightMargin(-333.0005)
layout:setTopMargin(-357.0013)
layout:setBottomMargin(357.0013)
innerProject.animation:setTimeSpeed(1.0000)
node_player_info_1:runAction(innerProject.animation)
node_1:addChild(node_player_info_1)

--Create node_2
local node_2=cc.Node:create()
node_2:setName("node_2")
node_2:setTag(936)
node_2:setCascadeColorEnabled(true)
node_2:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(node_2)
panel:addChild(node_2)

--Create btn_player_info_2
local btn_player_info_2 = ccui.Button:create()
btn_player_info_2:ignoreContentAdaptWithSize(false)
btn_player_info_2:loadTextureNormal("common/btn/com_btn_green3_0.png",0)
btn_player_info_2:loadTexturePressed("common/btn/com_btn_green3_0.png",0)
btn_player_info_2:loadTextureDisabled("common/btn/com_btn_green3_0.png",0)
btn_player_info_2:setTitleFontSize(14)
btn_player_info_2:setTitleColor({r = 65, g = 65, b = 70})
btn_player_info_2:setLayoutComponentEnabled(true)
btn_player_info_2:setName("btn_player_info_2")
btn_player_info_2:setTag(937)
btn_player_info_2:setCascadeColorEnabled(true)
btn_player_info_2:setCascadeOpacityEnabled(true)
btn_player_info_2:setPosition(-333.0000, 28.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_player_info_2)
layout:setSize({width = 126.0000, height = 64.0000})
layout:setLeftMargin(-396.0000)
layout:setRightMargin(270.0000)
layout:setTopMargin(-60.0000)
layout:setBottomMargin(-4.0000)
node_2:addChild(btn_player_info_2)

--Create spr_check_info
local spr_check_info = cc.Sprite:create("hall/friend/fr_btn_ck.png")
spr_check_info:setName("spr_check_info")
spr_check_info:setTag(938)
spr_check_info:setCascadeColorEnabled(true)
spr_check_info:setCascadeOpacityEnabled(true)
spr_check_info:setPosition(63.0000, 35.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_check_info)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5469)
layout:setPercentWidth(0.6190)
layout:setPercentHeight(0.6563)
layout:setSize({width = 78.0000, height = 42.0000})
layout:setLeftMargin(24.0000)
layout:setRightMargin(24.0000)
layout:setTopMargin(8.0000)
layout:setBottomMargin(14.0000)
spr_check_info:setBlendFunc({src = 1, dst = 771})
btn_player_info_2:addChild(spr_check_info)

--Create node_player_info_2
innerCSD = require("ui.playerinfo.uigameplayerinfo")
innerProject = innerCSD.create(callBackProvider)
local node_player_info_2 = innerProject.root
node_player_info_2.animation = innerProject.animation
node_player_info_2:setName("node_player_info_2")
node_player_info_2:setTag(939)
node_player_info_2:setCascadeColorEnabled(true)
node_player_info_2:setCascadeOpacityEnabled(true)
node_player_info_2:setPosition(-333.0000, 357.0086)
layout = ccui.LayoutComponent:bindLayoutComponent(node_player_info_2)
layout:setLeftMargin(-333.0000)
layout:setRightMargin(333.0000)
layout:setTopMargin(-357.0086)
layout:setBottomMargin(357.0086)
innerProject.animation:setTimeSpeed(1.0000)
node_player_info_2:runAction(innerProject.animation)
node_2:addChild(node_player_info_2)

--Create node_3
local node_3=cc.Node:create()
node_3:setName("node_3")
node_3:setTag(957)
node_3:setCascadeColorEnabled(true)
node_3:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(node_3)
panel:addChild(node_3)

--Create btn_player_info_3
local btn_player_info_3 = ccui.Button:create()
btn_player_info_3:ignoreContentAdaptWithSize(false)
btn_player_info_3:loadTextureNormal("common/btn/com_btn_green3_0.png",0)
btn_player_info_3:loadTexturePressed("common/btn/com_btn_green3_0.png",0)
btn_player_info_3:loadTextureDisabled("common/btn/com_btn_green3_0.png",0)
btn_player_info_3:setTitleFontSize(14)
btn_player_info_3:setTitleColor({r = 65, g = 65, b = 70})
btn_player_info_3:setLayoutComponentEnabled(true)
btn_player_info_3:setName("btn_player_info_3")
btn_player_info_3:setTag(958)
btn_player_info_3:setCascadeColorEnabled(true)
btn_player_info_3:setCascadeOpacityEnabled(true)
btn_player_info_3:setPosition(-333.0000, -30.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_player_info_3)
layout:setSize({width = 126.0000, height = 64.0000})
layout:setLeftMargin(-396.0000)
layout:setRightMargin(270.0000)
layout:setTopMargin(-2.0000)
layout:setBottomMargin(-62.0000)
node_3:addChild(btn_player_info_3)

--Create spr_check_info
local spr_check_info = cc.Sprite:create("hall/friend/fr_btn_ck.png")
spr_check_info:setName("spr_check_info")
spr_check_info:setTag(959)
spr_check_info:setCascadeColorEnabled(true)
spr_check_info:setCascadeOpacityEnabled(true)
spr_check_info:setPosition(63.0000, 35.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_check_info)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5469)
layout:setPercentWidth(0.6190)
layout:setPercentHeight(0.6563)
layout:setSize({width = 78.0000, height = 42.0000})
layout:setLeftMargin(24.0000)
layout:setRightMargin(24.0000)
layout:setTopMargin(8.0000)
layout:setBottomMargin(14.0000)
spr_check_info:setBlendFunc({src = 1, dst = 771})
btn_player_info_3:addChild(spr_check_info)

--Create node_player_info_3
innerCSD = require("ui.playerinfo.uigameplayerinfo")
innerProject = innerCSD.create(callBackProvider)
local node_player_info_3 = innerProject.root
node_player_info_3.animation = innerProject.animation
node_player_info_3:setName("node_player_info_3")
node_player_info_3:setTag(960)
node_player_info_3:setCascadeColorEnabled(true)
node_player_info_3:setCascadeOpacityEnabled(true)
node_player_info_3:setPosition(-333.0000, -200.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_player_info_3)
layout:setLeftMargin(-333.0000)
layout:setRightMargin(333.0000)
layout:setTopMargin(200.0000)
layout:setBottomMargin(-200.0000)
innerProject.animation:setTimeSpeed(1.0000)
node_player_info_3:runAction(innerProject.animation)
node_3:addChild(node_player_info_3)

--Create node_4
local node_4=cc.Node:create()
node_4:setName("node_4")
node_4:setTag(978)
node_4:setCascadeColorEnabled(true)
node_4:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(node_4)
panel:addChild(node_4)

--Create btn_player_info_4
local btn_player_info_4 = ccui.Button:create()
btn_player_info_4:ignoreContentAdaptWithSize(false)
btn_player_info_4:loadTextureNormal("common/btn/com_btn_green3_0.png",0)
btn_player_info_4:loadTexturePressed("common/btn/com_btn_green3_0.png",0)
btn_player_info_4:loadTextureDisabled("common/btn/com_btn_green3_0.png",0)
btn_player_info_4:setTitleFontSize(14)
btn_player_info_4:setTitleColor({r = 65, g = 65, b = 70})
btn_player_info_4:setLayoutComponentEnabled(true)
btn_player_info_4:setName("btn_player_info_4")
btn_player_info_4:setTag(979)
btn_player_info_4:setCascadeColorEnabled(true)
btn_player_info_4:setCascadeOpacityEnabled(true)
btn_player_info_4:setPosition(333.0000, -30.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_player_info_4)
layout:setSize({width = 126.0000, height = 64.0000})
layout:setLeftMargin(270.0000)
layout:setRightMargin(-396.0000)
layout:setTopMargin(-2.0000)
layout:setBottomMargin(-62.0000)
node_4:addChild(btn_player_info_4)

--Create spr_check_info
local spr_check_info = cc.Sprite:create("hall/friend/fr_btn_ck.png")
spr_check_info:setName("spr_check_info")
spr_check_info:setTag(980)
spr_check_info:setCascadeColorEnabled(true)
spr_check_info:setCascadeOpacityEnabled(true)
spr_check_info:setPosition(63.0000, 35.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_check_info)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5469)
layout:setPercentWidth(0.6190)
layout:setPercentHeight(0.6563)
layout:setSize({width = 78.0000, height = 42.0000})
layout:setLeftMargin(24.0000)
layout:setRightMargin(24.0000)
layout:setTopMargin(8.0000)
layout:setBottomMargin(14.0000)
spr_check_info:setBlendFunc({src = 1, dst = 771})
btn_player_info_4:addChild(spr_check_info)

--Create node_player_info_4
innerCSD = require("ui.playerinfo.uigameplayerinfo")
innerProject = innerCSD.create(callBackProvider)
local node_player_info_4 = innerProject.root
node_player_info_4.animation = innerProject.animation
node_player_info_4:setName("node_player_info_4")
node_player_info_4:setTag(981)
node_player_info_4:setCascadeColorEnabled(true)
node_player_info_4:setCascadeOpacityEnabled(true)
node_player_info_4:setPosition(333.0000, -200.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_player_info_4)
layout:setLeftMargin(333.0000)
layout:setRightMargin(-333.0000)
layout:setTopMargin(200.0000)
layout:setBottomMargin(-200.0000)
innerProject.animation:setTimeSpeed(1.0000)
node_player_info_4:runAction(innerProject.animation)
node_4:addChild(node_player_info_4)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

