--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorType(1)
panel:setBackGroundColor({r = 150, g = 200, b = 255})
panel:setBackGroundColorOpacity(102)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(57)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
Node:addChild(panel)

--Create image_formbg
local image_formbg = ccui.ImageView:create()
image_formbg:ignoreContentAdaptWithSize(false)
image_formbg:loadTexture("battle/form/form_box_1.png",0)
image_formbg:setScale9Enabled(true)
image_formbg:setCapInsets({x = 41, y = 28, width = 44, height = 30})
image_formbg:setLayoutComponentEnabled(true)
image_formbg:setName("image_formbg")
image_formbg:setTag(35)
image_formbg:setCascadeColorEnabled(true)
image_formbg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(image_formbg)
layout:setSize({width = 126.0000, height = 86.0000})
layout:setLeftMargin(-63.0000)
layout:setRightMargin(-63.0000)
layout:setTopMargin(-43.0000)
layout:setBottomMargin(-43.0000)
panel:addChild(image_formbg)

--Create spr_fish
local spr_fish = cc.Sprite:create("battle/form/pic_fishid/fishid_1.png")
spr_fish:setName("spr_fish")
spr_fish:setTag(106)
spr_fish:setCascadeColorEnabled(true)
spr_fish:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_fish)
layout:setSize({width = 126.0000, height = 86.0000})
layout:setLeftMargin(-63.0000)
layout:setRightMargin(-63.0000)
layout:setTopMargin(-43.0000)
layout:setBottomMargin(-43.0000)
spr_fish:setBlendFunc({src = 1, dst = 771})
panel:addChild(spr_fish)

--Create fnt_rate
local fnt_rate = ccui.TextBMFont:create()
fnt_rate:setFntFile("fnt/Common_num_01.fnt")
fnt_rate:setString([[1000]])
fnt_rate:setLayoutComponentEnabled(true)
fnt_rate:setName("fnt_rate")
fnt_rate:setTag(107)
fnt_rate:setCascadeColorEnabled(true)
fnt_rate:setCascadeOpacityEnabled(true)
fnt_rate:setAnchorPoint(1.0000, 0.5000)
fnt_rate:setPosition(54.7357, -23.0176)
layout = ccui.LayoutComponent:bindLayoutComponent(fnt_rate)
layout:setSize({width = 68.0000, height = 28.0000})
layout:setLeftMargin(-13.2643)
layout:setRightMargin(-54.7357)
layout:setTopMargin(9.0176)
layout:setBottomMargin(-37.0176)
panel:addChild(fnt_rate)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

