--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create image_lotterypanel_bg
local image_lotterypanel_bg = ccui.ImageView:create()
image_lotterypanel_bg:ignoreContentAdaptWithSize(false)
image_lotterypanel_bg:loadTexture("battle/gunupgrade/bl_pic_maxbg.png",0)
image_lotterypanel_bg:setScale9Enabled(true)
image_lotterypanel_bg:setCapInsets({x = 23, y = 63, width = 5, height = 1})
image_lotterypanel_bg:setLayoutComponentEnabled(true)
image_lotterypanel_bg:setName("image_lotterypanel_bg")
image_lotterypanel_bg:setTag(66)
image_lotterypanel_bg:setCascadeColorEnabled(true)
image_lotterypanel_bg:setCascadeOpacityEnabled(true)
image_lotterypanel_bg:setAnchorPoint(0.0000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(image_lotterypanel_bg)
layout:setSize({width = 362.0000, height = 126.0000})
layout:setRightMargin(-362.0000)
layout:setTopMargin(-63.0000)
layout:setBottomMargin(-63.0000)
Node:addChild(image_lotterypanel_bg)

--Create node_animation
local node_animation=cc.Node:create()
node_animation:setName("node_animation")
node_animation:setTag(99)
node_animation:setCascadeColorEnabled(true)
node_animation:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(node_animation)
layout:setRightMargin(362.0000)
layout:setTopMargin(126.0000)
image_lotterypanel_bg:addChild(node_animation)

--Create unlockgun2_00_1_0
local unlockgun2_00_1_0 = cc.Sprite:create("battle/effect/unlockgun2.png")
unlockgun2_00_1_0:setName("unlockgun2_00_1_0")
unlockgun2_00_1_0:setTag(186)
unlockgun2_00_1_0:setCascadeColorEnabled(true)
unlockgun2_00_1_0:setCascadeOpacityEnabled(true)
unlockgun2_00_1_0:setPosition(180.0000, 63.8508)
layout = ccui.LayoutComponent:bindLayoutComponent(unlockgun2_00_1_0)
layout:setSize({width = 370.0000, height = 200.0000})
layout:setLeftMargin(-5.0000)
layout:setRightMargin(-365.0000)
layout:setTopMargin(-163.8508)
layout:setBottomMargin(-36.1492)
unlockgun2_00_1_0:setBlendFunc({src = 770, dst = 1})
node_animation:addChild(unlockgun2_00_1_0)

--Create unlockgun2_00_1
local unlockgun2_00_1 = cc.Sprite:create("battle/effect/unlockgun2.png")
unlockgun2_00_1:setName("unlockgun2_00_1")
unlockgun2_00_1:setTag(185)
unlockgun2_00_1:setCascadeColorEnabled(true)
unlockgun2_00_1:setCascadeOpacityEnabled(true)
unlockgun2_00_1:setPosition(180.0000, 63.8508)
unlockgun2_00_1:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(unlockgun2_00_1)
layout:setSize({width = 370.0000, height = 200.0000})
layout:setLeftMargin(-5.0000)
layout:setRightMargin(-365.0000)
layout:setTopMargin(-163.8508)
layout:setBottomMargin(-36.1492)
unlockgun2_00_1:setBlendFunc({src = 770, dst = 1})
node_animation:addChild(unlockgun2_00_1)

--Create node_spr
local node_spr=cc.Node:create()
node_spr:setName("node_spr")
node_spr:setTag(110)
node_spr:setCascadeColorEnabled(true)
node_spr:setCascadeOpacityEnabled(true)
node_spr:setPosition(0.0000, 63.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_spr)
layout:setPositionPercentY(0.5000)
layout:setRightMargin(362.0000)
layout:setTopMargin(63.0000)
layout:setBottomMargin(63.0000)
image_lotterypanel_bg:addChild(node_spr)

--Create spr_words_jc
local spr_words_jc = cc.Sprite:create("battle/gunupgrade/bl_pic_words_jc.png")
spr_words_jc:setName("spr_words_jc")
spr_words_jc:setTag(70)
spr_words_jc:setCascadeColorEnabled(true)
spr_words_jc:setCascadeOpacityEnabled(true)
spr_words_jc:setPosition(117.2806, -22.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_words_jc)
layout:setSize({width = 48.0000, height = 26.0000})
layout:setLeftMargin(93.2806)
layout:setRightMargin(-141.2806)
layout:setTopMargin(9.0000)
layout:setBottomMargin(-35.0000)
spr_words_jc:setBlendFunc({src = 1, dst = 771})
node_spr:addChild(spr_words_jc)

--Create spr_coins
local spr_coins = cc.Sprite:create("common/com_icon_coins.png")
spr_coins:setName("spr_coins")
spr_coins:setTag(114)
spr_coins:setCascadeColorEnabled(true)
spr_coins:setCascadeOpacityEnabled(true)
spr_coins:setPosition(163.5545, -22.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_coins)
layout:setSize({width = 34.0000, height = 34.0000})
layout:setLeftMargin(146.5545)
layout:setRightMargin(-180.5545)
layout:setTopMargin(5.0000)
layout:setBottomMargin(-39.0000)
spr_coins:setBlendFunc({src = 1, dst = 771})
node_spr:addChild(spr_coins)

--Create fnt_allcoin
local fnt_allcoin = ccui.TextBMFont:create()
fnt_allcoin:setFntFile("fnt/Common_num_01.fnt")
fnt_allcoin:setString([[0]])
fnt_allcoin:setLayoutComponentEnabled(true)
fnt_allcoin:setName("fnt_allcoin")
fnt_allcoin:setTag(115)
fnt_allcoin:setCascadeColorEnabled(true)
fnt_allcoin:setCascadeOpacityEnabled(true)
fnt_allcoin:setAnchorPoint(0.0000, 0.5000)
fnt_allcoin:setPosition(178.6837, -22.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(fnt_allcoin)
layout:setSize({width = 17.0000, height = 28.0000})
layout:setLeftMargin(178.6837)
layout:setRightMargin(-195.6837)
layout:setTopMargin(8.0001)
layout:setBottomMargin(-36.0001)
node_spr:addChild(fnt_allcoin)

--Create image_bar_bg
local image_bar_bg = ccui.ImageView:create()
image_bar_bg:ignoreContentAdaptWithSize(false)
image_bar_bg:loadTexture("battle/gunupgrade/bl_pic_bar_bg.png",0)
image_bar_bg:setScale9Enabled(true)
image_bar_bg:setCapInsets({x = 12, y = 10, width = 18, height = 8})
image_bar_bg:setLayoutComponentEnabled(true)
image_bar_bg:setName("image_bar_bg")
image_bar_bg:setTag(77)
image_bar_bg:setCascadeColorEnabled(true)
image_bar_bg:setCascadeOpacityEnabled(true)
image_bar_bg:setPosition(227.8564, 16.9840)
layout = ccui.LayoutComponent:bindLayoutComponent(image_bar_bg)
layout:setSize({width = 163.0000, height = 28.0000})
layout:setLeftMargin(146.3564)
layout:setRightMargin(-309.3564)
layout:setTopMargin(-30.9840)
layout:setBottomMargin(2.9840)
node_spr:addChild(image_bar_bg)

--Create spr_words_jjy
local spr_words_jjy = cc.Sprite:create("battle/gunupgrade/bl_pic_words_jjy.png")
spr_words_jjy:setName("spr_words_jjy")
spr_words_jjy:setTag(69)
spr_words_jjy:setCascadeColorEnabled(true)
spr_words_jjy:setCascadeOpacityEnabled(true)
spr_words_jjy:setPosition(-37.1536, 14.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_words_jjy)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(-0.2279)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4294)
layout:setPercentHeight(0.9286)
layout:setSize({width = 70.0000, height = 26.0000})
layout:setLeftMargin(-72.1536)
layout:setRightMargin(165.1536)
layout:setTopMargin(1.0000)
layout:setBottomMargin(1.0000)
spr_words_jjy:setBlendFunc({src = 1, dst = 771})
image_bar_bg:addChild(spr_words_jjy)

--Create bar_LoadingBar
local bar_LoadingBar = ccui.LoadingBar:create()
bar_LoadingBar:loadTexture("battle/gunupgrade/bl_pic_bar_blood.png",0)
bar_LoadingBar:ignoreContentAdaptWithSize(false)
bar_LoadingBar:setPercent(49)
bar_LoadingBar:setLayoutComponentEnabled(true)
bar_LoadingBar:setName("bar_LoadingBar")
bar_LoadingBar:setTag(76)
bar_LoadingBar:setCascadeColorEnabled(true)
bar_LoadingBar:setCascadeOpacityEnabled(true)
bar_LoadingBar:setPosition(80.9999, 14.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bar_LoadingBar)
layout:setPositionPercentX(0.4969)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9571)
layout:setPercentHeight(0.7857)
layout:setSize({width = 156.0000, height = 22.0000})
layout:setLeftMargin(2.9999)
layout:setRightMargin(4.0001)
layout:setTopMargin(3.0000)
layout:setBottomMargin(3.0000)
image_bar_bg:addChild(bar_LoadingBar)

--Create fnt_aimNun
local fnt_aimNun = ccui.TextBMFont:create()
fnt_aimNun:setFntFile("fnt/Common_num_01.fnt")
fnt_aimNun:setString([[1]])
fnt_aimNun:setLayoutComponentEnabled(true)
fnt_aimNun:setName("fnt_aimNun")
fnt_aimNun:setTag(81)
fnt_aimNun:setCascadeColorEnabled(true)
fnt_aimNun:setCascadeOpacityEnabled(true)
fnt_aimNun:setAnchorPoint(0.0000, 0.5000)
fnt_aimNun:setPosition(89.0000, 13.6061)
fnt_aimNun:setScaleX(0.9000)
fnt_aimNun:setScaleY(0.9000)
layout = ccui.LayoutComponent:bindLayoutComponent(fnt_aimNun)
layout:setPositionPercentX(0.5460)
layout:setPositionPercentY(0.4859)
layout:setPercentWidth(0.1043)
layout:setPercentHeight(1.0000)
layout:setSize({width = 17.0000, height = 28.0000})
layout:setLeftMargin(89.0000)
layout:setRightMargin(57.0000)
layout:setTopMargin(0.3939)
layout:setBottomMargin(-0.3939)
image_bar_bg:addChild(fnt_aimNun)

--Create fnt_slash
local fnt_slash = ccui.TextBMFont:create()
fnt_slash:setFntFile("fnt/Common_num_01.fnt")
fnt_slash:setString([[&]])
fnt_slash:setLayoutComponentEnabled(true)
fnt_slash:setName("fnt_slash")
fnt_slash:setTag(80)
fnt_slash:setCascadeColorEnabled(true)
fnt_slash:setCascadeOpacityEnabled(true)
fnt_slash:setPosition(78.0000, 13.6061)
fnt_slash:setScaleX(0.9000)
fnt_slash:setScaleY(0.9000)
layout = ccui.LayoutComponent:bindLayoutComponent(fnt_slash)
layout:setPositionPercentX(0.4785)
layout:setPositionPercentY(0.4859)
layout:setPercentWidth(0.1043)
layout:setPercentHeight(1.0000)
layout:setSize({width = 17.0000, height = 28.0000})
layout:setLeftMargin(69.5000)
layout:setRightMargin(76.5000)
layout:setTopMargin(0.3939)
layout:setBottomMargin(-0.3939)
image_bar_bg:addChild(fnt_slash)

--Create fnt_curNum
local fnt_curNum = ccui.TextBMFont:create()
fnt_curNum:setFntFile("fnt/Common_num_01.fnt")
fnt_curNum:setString([[0]])
fnt_curNum:setLayoutComponentEnabled(true)
fnt_curNum:setName("fnt_curNum")
fnt_curNum:setTag(78)
fnt_curNum:setCascadeColorEnabled(true)
fnt_curNum:setCascadeOpacityEnabled(true)
fnt_curNum:setAnchorPoint(1.0000, 0.5000)
fnt_curNum:setPosition(67.0001, 13.6061)
fnt_curNum:setScaleX(0.9000)
fnt_curNum:setScaleY(0.9000)
layout = ccui.LayoutComponent:bindLayoutComponent(fnt_curNum)
layout:setPositionPercentX(0.4110)
layout:setPositionPercentY(0.4859)
layout:setPercentWidth(0.1043)
layout:setPercentHeight(1.0000)
layout:setSize({width = 17.0000, height = 28.0000})
layout:setLeftMargin(50.0001)
layout:setRightMargin(95.9999)
layout:setTopMargin(0.3939)
layout:setBottomMargin(-0.3939)
image_bar_bg:addChild(fnt_curNum)

--Create spr_startlottery
local spr_startlottery = cc.Sprite:create("battle/gunupgrade/bl_pic_djcj.png")
spr_startlottery:setName("spr_startlottery")
spr_startlottery:setTag(366)
spr_startlottery:setCascadeColorEnabled(true)
spr_startlottery:setCascadeOpacityEnabled(true)
spr_startlottery:setPosition(176.0000, 23.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_startlottery)
layout:setSize({width = 132.0000, height = 44.0000})
layout:setLeftMargin(110.0000)
layout:setRightMargin(-242.0000)
layout:setTopMargin(-45.0000)
layout:setBottomMargin(1.0000)
spr_startlottery:setBlendFunc({src = 1, dst = 771})
node_spr:addChild(spr_startlottery)

--Create btn_lottery
local btn_lottery = ccui.Button:create()
btn_lottery:ignoreContentAdaptWithSize(false)
btn_lottery:loadTextureNormal("battle/gunupgrade/bl_btn_lottery.png",0)
btn_lottery:loadTexturePressed("battle/gunupgrade/bl_btn_lottery.png",0)
btn_lottery:loadTextureDisabled("battle/gunupgrade/bl_btn_lottery.png",0)
btn_lottery:setTitleFontSize(14)
btn_lottery:setTitleColor({r = 65, g = 65, b = 70})
btn_lottery:setScale9Enabled(true)
btn_lottery:setCapInsets({x = 15, y = 11, width = 42, height = 56})
btn_lottery:setLayoutComponentEnabled(true)
btn_lottery:setName("btn_lottery")
btn_lottery:setTag(67)
btn_lottery:setCascadeColorEnabled(true)
btn_lottery:setCascadeOpacityEnabled(true)
btn_lottery:setPosition(35.0005, 2.2117)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_lottery)
layout:setSize({width = 72.0000, height = 78.0000})
layout:setLeftMargin(-0.9995)
layout:setRightMargin(-71.0005)
layout:setTopMargin(-41.2117)
layout:setBottomMargin(-36.7883)
Node:addChild(btn_lottery)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(90)
result['animation']:setTimeSpeed(1.0000)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(180.0000)
localFrame:setY(63.8508)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(50)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(180.0000)
localFrame:setY(63.8508)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(80)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(180.0000)
localFrame:setY(63.8508)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(180.0000)
localFrame:setY(63.8508)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(unlockgun2_00_1_0)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(50)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.2000)
localFrame:setScaleY(1.2000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(80)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(unlockgun2_00_1_0)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(50)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(80)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(unlockgun2_00_1_0)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(50)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(80)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(128)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(unlockgun2_00_1_0)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(180.0000)
localFrame:setY(63.8508)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(18)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(180.0000)
localFrame:setY(63.8508)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(180.0000)
localFrame:setY(63.8508)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(unlockgun2_00_1)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(18)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(unlockgun2_00_1)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(18)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(unlockgun2_00_1)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(18)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(unlockgun2_00_1)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(176.0000)
localFrame:setY(23.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(8)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(173.7653)
localFrame:setY(39.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(15)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setX(175.0596)
localFrame:setY(24.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(22)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(176.0000)
localFrame:setY(38.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setX(176.0000)
localFrame:setY(23.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(spr_startlottery)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(8)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(15)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setScaleX(1.0286)
localFrame:setScaleY(0.9429)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(22)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.1000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setScaleX(1.1000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(37)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(spr_startlottery)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(8)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(3.0000)
localFrame:setSkewY(3.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(15)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(22)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(-3.0000)
localFrame:setSkewY(-3.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(spr_startlottery)
--Create Animation List
local LotteryPanel = {name="LotteryPanel", startIndex=0, endIndex=90}
result['animation']:addAnimationInfo(LotteryPanel)

result['root'] = Node
return result;
end

return Result

