--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorType(1)
panel:setBackGroundColor({r = 150, g = 200, b = 255})
panel:setBackGroundColorOpacity(102)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(6670)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setPosition(-0.0007, 19.9997)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setLeftMargin(-0.0007)
layout:setRightMargin(0.0007)
layout:setTopMargin(-19.9997)
layout:setBottomMargin(19.9997)
Node:addChild(panel)

--Create btn_autofire
local btn_autofire = ccui.Button:create()
btn_autofire:ignoreContentAdaptWithSize(false)
btn_autofire:loadTextureNormal("battle/gunchange/bl_btn_bg.png",0)
btn_autofire:loadTexturePressed("battle/gunchange/bl_btn_bg.png",0)
btn_autofire:loadTextureDisabled("battle/gunchange/bl_btn_bg.png",0)
btn_autofire:setTitleFontSize(14)
btn_autofire:setTitleColor({r = 65, g = 65, b = 70})
btn_autofire:setLayoutComponentEnabled(true)
btn_autofire:setName("btn_autofire")
btn_autofire:setTag(70)
btn_autofire:setCascadeColorEnabled(true)
btn_autofire:setCascadeOpacityEnabled(true)
btn_autofire:setPosition(-105.0000, 77.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_autofire)
layout:setSize({width = 122.0000, height = 110.0000})
layout:setLeftMargin(-166.0000)
layout:setRightMargin(44.0000)
layout:setTopMargin(-132.0000)
layout:setBottomMargin(22.0000)
panel:addChild(btn_autofire)

--Create spr_autofire
local spr_autofire = cc.Sprite:create("battle/gunchange/bl_pic_auto.png")
spr_autofire:setName("spr_autofire")
spr_autofire:setTag(71)
spr_autofire:setCascadeColorEnabled(true)
spr_autofire:setCascadeOpacityEnabled(true)
spr_autofire:setPosition(61.0000, 55.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_autofire)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.7869)
layout:setPercentHeight(0.8727)
layout:setSize({width = 96.0000, height = 96.0000})
layout:setLeftMargin(13.0000)
layout:setRightMargin(13.0000)
layout:setTopMargin(7.0000)
layout:setBottomMargin(7.0000)
spr_autofire:setBlendFunc({src = 1, dst = 771})
btn_autofire:addChild(spr_autofire)

--Create spr_cancelauto
local spr_cancelauto = cc.Sprite:create("battle/gunchange/bl_pic_cancelauto.png")
spr_cancelauto:setName("spr_cancelauto")
spr_cancelauto:setTag(68)
spr_cancelauto:setCascadeColorEnabled(true)
spr_cancelauto:setCascadeOpacityEnabled(true)
spr_cancelauto:setPosition(61.0000, 55.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_cancelauto)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.7869)
layout:setPercentHeight(0.8727)
layout:setSize({width = 96.0000, height = 96.0000})
layout:setLeftMargin(13.0000)
layout:setRightMargin(13.0000)
layout:setTopMargin(7.0000)
layout:setBottomMargin(7.0000)
spr_cancelauto:setBlendFunc({src = 1, dst = 771})
btn_autofire:addChild(spr_cancelauto)

--Create btn_changecannon
local btn_changecannon = ccui.Button:create()
btn_changecannon:ignoreContentAdaptWithSize(false)
btn_changecannon:loadTextureNormal("battle/gunchange/bl_btn_bg.png",0)
btn_changecannon:loadTexturePressed("battle/gunchange/bl_btn_bg.png",0)
btn_changecannon:loadTextureDisabled("battle/gunchange/bl_btn_bg.png",0)
btn_changecannon:setTitleFontSize(14)
btn_changecannon:setTitleColor({r = 65, g = 65, b = 70})
btn_changecannon:setLayoutComponentEnabled(true)
btn_changecannon:setName("btn_changecannon")
btn_changecannon:setTag(72)
btn_changecannon:setCascadeColorEnabled(true)
btn_changecannon:setCascadeOpacityEnabled(true)
btn_changecannon:setPosition(105.0000, 77.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_changecannon)
layout:setSize({width = 122.0000, height = 110.0000})
layout:setLeftMargin(44.0000)
layout:setRightMargin(-166.0000)
layout:setTopMargin(-132.0000)
layout:setBottomMargin(22.0000)
panel:addChild(btn_changecannon)

--Create spr_changecannon
local spr_changecannon = cc.Sprite:create("battle/gunchange/bl_pic_change.png")
spr_changecannon:setName("spr_changecannon")
spr_changecannon:setTag(73)
spr_changecannon:setCascadeColorEnabled(true)
spr_changecannon:setCascadeOpacityEnabled(true)
spr_changecannon:setPosition(61.0000, 55.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_changecannon)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.7869)
layout:setPercentHeight(0.8727)
layout:setSize({width = 96.0000, height = 96.0000})
layout:setLeftMargin(13.0000)
layout:setRightMargin(13.0000)
layout:setTopMargin(7.0000)
layout:setBottomMargin(7.0000)
spr_changecannon:setBlendFunc({src = 1, dst = 771})
btn_changecannon:addChild(spr_changecannon)

--Create btn_face
local btn_face = ccui.Button:create()
btn_face:ignoreContentAdaptWithSize(false)
btn_face:loadTextureNormal("battle/gunchange/bl_btn_bg.png",0)
btn_face:loadTexturePressed("battle/gunchange/bl_btn_bg.png",0)
btn_face:loadTextureDisabled("battle/gunchange/bl_btn_bg.png",0)
btn_face:setTitleFontSize(14)
btn_face:setTitleColor({r = 65, g = 65, b = 70})
btn_face:setLayoutComponentEnabled(true)
btn_face:setName("btn_face")
btn_face:setTag(25)
btn_face:setCascadeColorEnabled(true)
btn_face:setCascadeOpacityEnabled(true)
btn_face:setPosition(0.0000, 138.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_face)
layout:setPositionPercentXEnabled(true)
layout:setSize({width = 122.0000, height = 110.0000})
layout:setLeftMargin(-61.0000)
layout:setRightMargin(-61.0000)
layout:setTopMargin(-193.0000)
layout:setBottomMargin(83.0000)
panel:addChild(btn_face)

--Create spr_emoji
local spr_emoji = cc.Sprite:create("battle/gunchange/bl_pic_emoji.png")
spr_emoji:setName("spr_emoji")
spr_emoji:setTag(26)
spr_emoji:setCascadeColorEnabled(true)
spr_emoji:setCascadeOpacityEnabled(true)
spr_emoji:setPosition(61.0000, 55.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_emoji)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.7869)
layout:setPercentHeight(0.8727)
layout:setSize({width = 96.0000, height = 96.0000})
layout:setLeftMargin(13.0000)
layout:setRightMargin(13.0000)
layout:setTopMargin(7.0000)
layout:setBottomMargin(7.0000)
spr_emoji:setBlendFunc({src = 1, dst = 771})
btn_face:addChild(spr_emoji)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

