--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create image_bg
local image_bg = ccui.ImageView:create()
image_bg:ignoreContentAdaptWithSize(false)
image_bg:loadTexture("battle/setbutton/bl_pic_bg.png",0)
image_bg:setScale9Enabled(true)
image_bg:setCapInsets({x = 24, y = 35, width = 3, height = 2})
image_bg:setLayoutComponentEnabled(true)
image_bg:setName("image_bg")
image_bg:setTag(1)
image_bg:setCascadeColorEnabled(true)
image_bg:setCascadeOpacityEnabled(true)
image_bg:setAnchorPoint(0.0700, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(image_bg)
layout:setSize({width = 115.0000, height = 342.0000})
layout:setLeftMargin(-8.0500)
layout:setRightMargin(-106.9500)
layout:setTopMargin(-171.0000)
layout:setBottomMargin(-171.0000)
Node:addChild(image_bg)

--Create btn_openlist
local btn_openlist = ccui.Button:create()
btn_openlist:ignoreContentAdaptWithSize(false)
btn_openlist:loadTextureNormal("battle/setbutton/bl_btn_open_0.png",0)
btn_openlist:loadTexturePressed("battle/setbutton/bl_btn_open_1.png",0)
btn_openlist:loadTextureDisabled("battle/setbutton/bl_btn_open_1.png",0)
btn_openlist:setTitleFontSize(14)
btn_openlist:setTitleColor({r = 65, g = 65, b = 70})
btn_openlist:setScale9Enabled(true)
btn_openlist:setCapInsets({x = 15, y = 11, width = 16, height = 54})
btn_openlist:setLayoutComponentEnabled(true)
btn_openlist:setName("btn_openlist")
btn_openlist:setTag(17)
btn_openlist:setCascadeColorEnabled(true)
btn_openlist:setCascadeOpacityEnabled(true)
btn_openlist:setAnchorPoint(1.0000, 0.5000)
btn_openlist:setPosition(8.0000, 171.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_openlist)
layout:setPositionPercentX(0.0696)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4000)
layout:setPercentHeight(0.2222)
layout:setSize({width = 46.0000, height = 76.0000})
layout:setLeftMargin(-38.0000)
layout:setRightMargin(107.0000)
layout:setTopMargin(133.0000)
layout:setBottomMargin(133.0000)
image_bg:addChild(btn_openlist)

--Create spr_triangle
local spr_triangle = cc.Sprite:create("battle/setbutton/btn_triangle.png")
spr_triangle:setName("spr_triangle")
spr_triangle:setTag(18)
spr_triangle:setCascadeColorEnabled(true)
spr_triangle:setCascadeOpacityEnabled(true)
spr_triangle:setPosition(30.0000, 38.0000)
spr_triangle:setRotationSkewX(180.0000)
spr_triangle:setRotationSkewY(180.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_triangle)
layout:setPositionPercentX(0.6522)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6522)
layout:setPercentHeight(0.5000)
layout:setSize({width = 30.0000, height = 38.0000})
layout:setLeftMargin(15.0000)
layout:setRightMargin(1.0000)
layout:setTopMargin(19.0000)
layout:setBottomMargin(19.0000)
spr_triangle:setBlendFunc({src = 1, dst = 771})
btn_openlist:addChild(spr_triangle)

--Create btn_pokedex
local btn_pokedex = ccui.Button:create()
btn_pokedex:ignoreContentAdaptWithSize(false)
btn_pokedex:loadTextureNormal("battle/setbutton/bl_btn_bg_0.png",0)
btn_pokedex:loadTexturePressed("battle/setbutton/bl_btn_bg_1.png",0)
btn_pokedex:loadTextureDisabled("battle/setbutton/bl_btn_bg_1.png",0)
btn_pokedex:setTitleFontSize(14)
btn_pokedex:setTitleColor({r = 65, g = 65, b = 70})
btn_pokedex:setScale9Enabled(true)
btn_pokedex:setCapInsets({x = 15, y = 11, width = 64, height = 72})
btn_pokedex:setLayoutComponentEnabled(true)
btn_pokedex:setName("btn_pokedex")
btn_pokedex:setTag(19)
btn_pokedex:setCascadeColorEnabled(true)
btn_pokedex:setCascadeOpacityEnabled(true)
btn_pokedex:setPosition(65.0000, 280.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_pokedex)
layout:setPositionPercentX(0.5652)
layout:setPositionPercentY(0.8187)
layout:setPercentWidth(0.8174)
layout:setPercentHeight(0.2749)
layout:setSize({width = 94.0000, height = 94.0000})
layout:setLeftMargin(18.0000)
layout:setRightMargin(3.0000)
layout:setTopMargin(15.0000)
layout:setBottomMargin(233.0000)
image_bg:addChild(btn_pokedex)

--Create spr_pokedex
local spr_pokedex = cc.Sprite:create("battle/setbutton/bl_pic_pokedex.png")
spr_pokedex:setName("spr_pokedex")
spr_pokedex:setTag(20)
spr_pokedex:setCascadeColorEnabled(true)
spr_pokedex:setCascadeOpacityEnabled(true)
spr_pokedex:setPosition(47.0000, 47.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_pokedex)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 94.0000, height = 94.0000})
spr_pokedex:setBlendFunc({src = 1, dst = 771})
btn_pokedex:addChild(spr_pokedex)

--Create spr_words_pokedex
local spr_words_pokedex = cc.Sprite:create("battle/setbutton/bl_pic_words_pokedex.png")
spr_words_pokedex:setName("spr_words_pokedex")
spr_words_pokedex:setTag(21)
spr_words_pokedex:setCascadeColorEnabled(true)
spr_words_pokedex:setCascadeOpacityEnabled(true)
spr_words_pokedex:setPosition(47.0000, 14.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_words_pokedex)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1489)
layout:setPercentWidth(0.6064)
layout:setPercentHeight(0.3511)
layout:setSize({width = 57.0000, height = 33.0000})
layout:setLeftMargin(18.5000)
layout:setRightMargin(18.5000)
layout:setTopMargin(63.5000)
layout:setBottomMargin(-2.5000)
spr_words_pokedex:setBlendFunc({src = 1, dst = 771})
btn_pokedex:addChild(spr_words_pokedex)

--Create btn_sound
local btn_sound = ccui.Button:create()
btn_sound:ignoreContentAdaptWithSize(false)
btn_sound:loadTextureNormal("battle/setbutton/bl_btn_bg_0.png",0)
btn_sound:loadTexturePressed("battle/setbutton/bl_btn_bg_1.png",0)
btn_sound:loadTextureDisabled("battle/setbutton/bl_btn_bg_1.png",0)
btn_sound:setTitleFontSize(14)
btn_sound:setTitleColor({r = 65, g = 65, b = 70})
btn_sound:setScale9Enabled(true)
btn_sound:setCapInsets({x = 15, y = 11, width = 64, height = 72})
btn_sound:setLayoutComponentEnabled(true)
btn_sound:setName("btn_sound")
btn_sound:setTag(25)
btn_sound:setCascadeColorEnabled(true)
btn_sound:setCascadeOpacityEnabled(true)
btn_sound:setPosition(65.0000, 173.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_sound)
layout:setPositionPercentX(0.5652)
layout:setPositionPercentY(0.5058)
layout:setPercentWidth(0.8174)
layout:setPercentHeight(0.2749)
layout:setSize({width = 94.0000, height = 94.0000})
layout:setLeftMargin(18.0000)
layout:setRightMargin(3.0000)
layout:setTopMargin(122.0000)
layout:setBottomMargin(126.0000)
image_bg:addChild(btn_sound)

--Create spr_sound
local spr_sound = cc.Sprite:create("battle/setbutton/bl_pic_sound.png")
spr_sound:setName("spr_sound")
spr_sound:setTag(26)
spr_sound:setCascadeColorEnabled(true)
spr_sound:setCascadeOpacityEnabled(true)
spr_sound:setPosition(47.0000, 47.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_sound)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 94.0000, height = 94.0000})
spr_sound:setBlendFunc({src = 1, dst = 771})
btn_sound:addChild(spr_sound)

--Create spr_words_sound
local spr_words_sound = cc.Sprite:create("battle/setbutton/bl_pic_words_sound.png")
spr_words_sound:setName("spr_words_sound")
spr_words_sound:setTag(27)
spr_words_sound:setCascadeColorEnabled(true)
spr_words_sound:setCascadeOpacityEnabled(true)
spr_words_sound:setPosition(47.0000, 14.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_words_sound)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1489)
layout:setPercentWidth(0.6064)
layout:setPercentHeight(0.3511)
layout:setSize({width = 57.0000, height = 33.0000})
layout:setLeftMargin(18.5000)
layout:setRightMargin(18.5000)
layout:setTopMargin(63.5000)
layout:setBottomMargin(-2.5000)
spr_words_sound:setBlendFunc({src = 1, dst = 771})
btn_sound:addChild(spr_words_sound)

--Create btn_exit
local btn_exit = ccui.Button:create()
btn_exit:ignoreContentAdaptWithSize(false)
btn_exit:loadTextureNormal("battle/setbutton/bl_btn_bg_0.png",0)
btn_exit:loadTexturePressed("battle/setbutton/bl_btn_bg_1.png",0)
btn_exit:loadTextureDisabled("battle/setbutton/bl_btn_bg_1.png",0)
btn_exit:setTitleFontSize(14)
btn_exit:setTitleColor({r = 65, g = 65, b = 70})
btn_exit:setScale9Enabled(true)
btn_exit:setCapInsets({x = 15, y = 11, width = 64, height = 72})
btn_exit:setLayoutComponentEnabled(true)
btn_exit:setName("btn_exit")
btn_exit:setTag(28)
btn_exit:setCascadeColorEnabled(true)
btn_exit:setCascadeOpacityEnabled(true)
btn_exit:setPosition(65.0000, 70.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_exit)
layout:setPositionPercentX(0.5652)
layout:setPositionPercentY(0.2047)
layout:setPercentWidth(0.8174)
layout:setPercentHeight(0.2749)
layout:setSize({width = 94.0000, height = 94.0000})
layout:setLeftMargin(18.0000)
layout:setRightMargin(3.0000)
layout:setTopMargin(225.0000)
layout:setBottomMargin(23.0000)
image_bg:addChild(btn_exit)

--Create spr_exit
local spr_exit = cc.Sprite:create("battle/setbutton/bl_pic_exit.png")
spr_exit:setName("spr_exit")
spr_exit:setTag(29)
spr_exit:setCascadeColorEnabled(true)
spr_exit:setCascadeOpacityEnabled(true)
spr_exit:setPosition(47.0000, 47.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_exit)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 94.0000, height = 94.0000})
spr_exit:setBlendFunc({src = 1, dst = 771})
btn_exit:addChild(spr_exit)

--Create spr_words_exit
local spr_words_exit = cc.Sprite:create("battle/setbutton/bl_pic_words_exit.png")
spr_words_exit:setName("spr_words_exit")
spr_words_exit:setTag(30)
spr_words_exit:setCascadeColorEnabled(true)
spr_words_exit:setCascadeOpacityEnabled(true)
spr_words_exit:setPosition(47.0000, 14.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_words_exit)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1489)
layout:setPercentWidth(0.6064)
layout:setPercentHeight(0.3511)
layout:setSize({width = 57.0000, height = 33.0000})
layout:setLeftMargin(18.5000)
layout:setRightMargin(18.5000)
layout:setTopMargin(63.5000)
layout:setBottomMargin(-2.5000)
spr_words_exit:setBlendFunc({src = 1, dst = 771})
btn_exit:addChild(spr_words_exit)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

