--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create bg
local bg=cc.Node:create()
bg:setName("bg")
bg:setTag(69)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
Node:addChild(bg)

--Create hall_room_bg_2_2
local hall_room_bg_2_2 = cc.Sprite:create("hall/room/hall_room_bg_1.png")
hall_room_bg_2_2:setName("hall_room_bg_2_2")
hall_room_bg_2_2:setTag(71)
hall_room_bg_2_2:setCascadeColorEnabled(true)
hall_room_bg_2_2:setCascadeOpacityEnabled(true)
hall_room_bg_2_2:setPosition(0.0000, 30.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_bg_2_2)
layout:setSize({width = 326.0000, height = 326.0000})
layout:setLeftMargin(-163.0000)
layout:setRightMargin(-163.0000)
layout:setTopMargin(-193.0000)
layout:setBottomMargin(-133.0000)
hall_room_bg_2_2:setBlendFunc({src = 1, dst = 771})
bg:addChild(hall_room_bg_2_2)

--Create hall_room_ground_8
local hall_room_ground_8 = cc.Sprite:create("hall/room/hall_room_ground.png")
hall_room_ground_8:setName("hall_room_ground_8")
hall_room_ground_8:setTag(78)
hall_room_ground_8:setCascadeColorEnabled(true)
hall_room_ground_8:setCascadeOpacityEnabled(true)
hall_room_ground_8:setAnchorPoint(1.0000, 0.5000)
hall_room_ground_8:setPosition(0.0000, -76.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_ground_8)
layout:setSize({width = 162.0000, height = 210.0000})
layout:setLeftMargin(-162.0000)
layout:setTopMargin(-29.0000)
layout:setBottomMargin(-181.0000)
hall_room_ground_8:setBlendFunc({src = 1, dst = 771})
bg:addChild(hall_room_ground_8)

--Create hall_room_ground_8_0
local hall_room_ground_8_0 = cc.Sprite:create("hall/room/hall_room_ground.png")
hall_room_ground_8_0:setName("hall_room_ground_8_0")
hall_room_ground_8_0:setTag(90)
hall_room_ground_8_0:setCascadeColorEnabled(true)
hall_room_ground_8_0:setCascadeOpacityEnabled(true)
hall_room_ground_8_0:setAnchorPoint(0.0000, 0.5000)
hall_room_ground_8_0:setPosition(0.0000, -76.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_ground_8_0)
layout:setSize({width = 162.0000, height = 210.0000})
layout:setRightMargin(-162.0000)
layout:setTopMargin(-29.0000)
layout:setBottomMargin(-181.0000)
hall_room_ground_8_0:setFlippedX(true)
hall_room_ground_8_0:setBlendFunc({src = 1, dst = 771})
bg:addChild(hall_room_ground_8_0)

--Create hall_room_bgdown_4_3_1
local hall_room_bgdown_4_3_1 = cc.Sprite:create("hall/room/hall_room_bgdown_4_3.png")
hall_room_bgdown_4_3_1:setName("hall_room_bgdown_4_3_1")
hall_room_bgdown_4_3_1:setTag(35)
hall_room_bgdown_4_3_1:setCascadeColorEnabled(true)
hall_room_bgdown_4_3_1:setCascadeOpacityEnabled(true)
hall_room_bgdown_4_3_1:setPosition(7.0002, -29.0000)
hall_room_bgdown_4_3_1:setScaleX(0.9000)
hall_room_bgdown_4_3_1:setScaleY(0.9000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_bgdown_4_3_1)
layout:setSize({width = 229.0000, height = 71.0000})
layout:setLeftMargin(-107.4998)
layout:setRightMargin(-121.5002)
layout:setTopMargin(-6.5000)
layout:setBottomMargin(-64.5000)
hall_room_bgdown_4_3_1:setBlendFunc({src = 1, dst = 771})
bg:addChild(hall_room_bgdown_4_3_1)

--Create hall_room_bgdown_1
local hall_room_bgdown_1 = cc.Sprite:create("hall/room/hall_room_bgdown_4_1.png")
hall_room_bgdown_1:setName("hall_room_bgdown_1")
hall_room_bgdown_1:setTag(70)
hall_room_bgdown_1:setCascadeColorEnabled(true)
hall_room_bgdown_1:setCascadeOpacityEnabled(true)
hall_room_bgdown_1:setAnchorPoint(1.0000, 0.0000)
hall_room_bgdown_1:setPosition(-66.5701, -34.7644)
hall_room_bgdown_1:setScaleX(0.9000)
hall_room_bgdown_1:setScaleY(0.9000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_bgdown_1)
layout:setSize({width = 118.0000, height = 152.0000})
layout:setLeftMargin(-184.5701)
layout:setRightMargin(66.5701)
layout:setTopMargin(-117.2356)
layout:setBottomMargin(-34.7644)
hall_room_bgdown_1:setBlendFunc({src = 1, dst = 771})
bg:addChild(hall_room_bgdown_1)

--Create hall_room_bgdown_2
local hall_room_bgdown_2 = cc.Sprite:create("hall/room/hall_room_bgdown_4_2.png")
hall_room_bgdown_2:setName("hall_room_bgdown_2")
hall_room_bgdown_2:setTag(427)
hall_room_bgdown_2:setCascadeColorEnabled(true)
hall_room_bgdown_2:setCascadeOpacityEnabled(true)
hall_room_bgdown_2:setAnchorPoint(0.1244, 0.1149)
hall_room_bgdown_2:setPosition(89.6188, -23.7951)
hall_room_bgdown_2:setRotationSkewX(-14.1969)
hall_room_bgdown_2:setRotationSkewY(-14.1942)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_bgdown_2)
layout:setSize({width = 133.0000, height = 110.0000})
layout:setLeftMargin(73.0736)
layout:setRightMargin(-206.0736)
layout:setTopMargin(-73.5659)
layout:setBottomMargin(-36.4341)
hall_room_bgdown_2:setBlendFunc({src = 1, dst = 771})
bg:addChild(hall_room_bgdown_2)

--Create spr_word_room
local spr_word_room = cc.Sprite:create("hall/room/title/room_title_4_1.png")
spr_word_room:setName("spr_word_room")
spr_word_room:setTag(87)
spr_word_room:setCascadeColorEnabled(true)
spr_word_room:setCascadeOpacityEnabled(true)
spr_word_room:setPosition(0.0000, -147.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_word_room)
layout:setSize({width = 88.0000, height = 36.0000})
layout:setLeftMargin(-44.0000)
layout:setRightMargin(-44.0000)
layout:setTopMargin(129.0000)
layout:setBottomMargin(-165.0000)
spr_word_room:setBlendFunc({src = 1, dst = 771})
bg:addChild(spr_word_room)

--Create hall_room_bgdown_4_4_1
local hall_room_bgdown_4_4_1 = cc.Sprite:create("hall/room/hall_room_bgdown_4_4.png")
hall_room_bgdown_4_4_1:setName("hall_room_bgdown_4_4_1")
hall_room_bgdown_4_4_1:setTag(31)
hall_room_bgdown_4_4_1:setCascadeColorEnabled(true)
hall_room_bgdown_4_4_1:setCascadeOpacityEnabled(true)
hall_room_bgdown_4_4_1:setPosition(12.1525, -31.6639)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_bgdown_4_4_1)
layout:setSize({width = 245.0000, height = 75.0000})
layout:setLeftMargin(-110.3475)
layout:setRightMargin(-134.6525)
layout:setTopMargin(-5.8361)
layout:setBottomMargin(-69.1639)
hall_room_bgdown_4_4_1:setBlendFunc({src = 1, dst = 771})
bg:addChild(hall_room_bgdown_4_4_1)

--Create light
local light=cc.Node:create()
light:setName("light")
light:setTag(94)
light:setCascadeColorEnabled(true)
light:setCascadeOpacityEnabled(true)
light:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(light)
bg:addChild(light)

--Create hall_room_title_pb_light_16
local hall_room_title_pb_light_16 = cc.Sprite:create("hall/room/hall_room_title_pb_light.png")
hall_room_title_pb_light_16:setName("hall_room_title_pb_light_16")
hall_room_title_pb_light_16:setTag(88)
hall_room_title_pb_light_16:setCascadeColorEnabled(true)
hall_room_title_pb_light_16:setCascadeOpacityEnabled(true)
hall_room_title_pb_light_16:setPosition(-72.0000, -149.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_pb_light_16)
layout:setSize({width = 16.0000, height = 24.0000})
layout:setLeftMargin(-80.0000)
layout:setRightMargin(64.0000)
layout:setTopMargin(137.0000)
layout:setBottomMargin(-161.0000)
hall_room_title_pb_light_16:setBlendFunc({src = 1, dst = 771})
light:addChild(hall_room_title_pb_light_16)

--Create hall_room_title_pb_light_16_0
local hall_room_title_pb_light_16_0 = cc.Sprite:create("hall/room/hall_room_title_pb_light.png")
hall_room_title_pb_light_16_0:setName("hall_room_title_pb_light_16_0")
hall_room_title_pb_light_16_0:setTag(91)
hall_room_title_pb_light_16_0:setCascadeColorEnabled(true)
hall_room_title_pb_light_16_0:setCascadeOpacityEnabled(true)
hall_room_title_pb_light_16_0:setPosition(72.0000, -149.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_pb_light_16_0)
layout:setSize({width = 16.0000, height = 24.0000})
layout:setLeftMargin(64.0000)
layout:setRightMargin(-80.0000)
layout:setTopMargin(137.0000)
layout:setBottomMargin(-161.0000)
hall_room_title_pb_light_16_0:setFlippedX(true)
hall_room_title_pb_light_16_0:setBlendFunc({src = 1, dst = 771})
light:addChild(hall_room_title_pb_light_16_0)

--Create hall_pic_room_locked_1
local hall_pic_room_locked_1 = cc.Sprite:create("hall/hallpic/hall_pic_room_locked.png")
hall_pic_room_locked_1:setName("hall_pic_room_locked_1")
hall_pic_room_locked_1:setTag(90)
hall_pic_room_locked_1:setCascadeColorEnabled(true)
hall_pic_room_locked_1:setCascadeOpacityEnabled(true)
hall_pic_room_locked_1:setPosition(85.0000, -145.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_pic_room_locked_1)
layout:setSize({width = 38.0000, height = 40.0000})
layout:setLeftMargin(66.0000)
layout:setRightMargin(-104.0000)
layout:setTopMargin(125.0000)
layout:setBottomMargin(-165.0000)
hall_pic_room_locked_1:setBlendFunc({src = 1, dst = 771})
bg:addChild(hall_pic_room_locked_1)

--Create room_effect
local room_effect=cc.Node:create()
room_effect:setName("room_effect")
room_effect:setTag(76)
room_effect:setCascadeColorEnabled(true)
room_effect:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(room_effect)
Node:addChild(room_effect)

--Create hall_room_effect_1_2_4
local hall_room_effect_1_2_4 = cc.Sprite:create("hall/room/hall_room_effect_4_1.png")
hall_room_effect_1_2_4:setName("hall_room_effect_1_2_4")
hall_room_effect_1_2_4:setTag(105)
hall_room_effect_1_2_4:setCascadeColorEnabled(true)
hall_room_effect_1_2_4:setCascadeOpacityEnabled(true)
hall_room_effect_1_2_4:setPosition(-80.0000, 122.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_effect_1_2_4)
layout:setSize({width = 66.0000, height = 69.0000})
layout:setLeftMargin(-113.0000)
layout:setRightMargin(47.0000)
layout:setTopMargin(-156.5000)
layout:setBottomMargin(87.5000)
hall_room_effect_1_2_4:setBlendFunc({src = 1, dst = 771})
room_effect:addChild(hall_room_effect_1_2_4)

--Create fish_1
local fish_1=cc.Node:create()
fish_1:setName("fish_1")
fish_1:setTag(93)
fish_1:setCascadeColorEnabled(true)
fish_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(fish_1)
Node:addChild(fish_1)

--Create hall_room_fish_5_hand1_16
local hall_room_fish_5_hand1_16 = cc.Sprite:create("hall/room/hall_room_fish_5_hand1.png")
hall_room_fish_5_hand1_16:setName("hall_room_fish_5_hand1_16")
hall_room_fish_5_hand1_16:setTag(70)
hall_room_fish_5_hand1_16:setCascadeColorEnabled(true)
hall_room_fish_5_hand1_16:setCascadeOpacityEnabled(true)
hall_room_fish_5_hand1_16:setPosition(61.6201, 96.1639)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_fish_5_hand1_16)
layout:setSize({width = 33.0000, height = 33.0000})
layout:setLeftMargin(45.1201)
layout:setRightMargin(-78.1201)
layout:setTopMargin(-112.6639)
layout:setBottomMargin(79.6639)
hall_room_fish_5_hand1_16:setBlendFunc({src = 1, dst = 771})
fish_1:addChild(hall_room_fish_5_hand1_16)

--Create hall_room_fish_2_7
local hall_room_fish_2_7 = cc.Sprite:create("hall/room/hall_room_fish_5.png")
hall_room_fish_2_7:setName("hall_room_fish_2_7")
hall_room_fish_2_7:setTag(77)
hall_room_fish_2_7:setCascadeColorEnabled(true)
hall_room_fish_2_7:setCascadeOpacityEnabled(true)
hall_room_fish_2_7:setPosition(27.0000, 100.0000)
hall_room_fish_2_7:setScaleX(0.9500)
hall_room_fish_2_7:setScaleY(0.8686)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_fish_2_7)
layout:setSize({width = 233.0000, height = 263.0000})
layout:setLeftMargin(-89.5000)
layout:setRightMargin(-143.5000)
layout:setTopMargin(-231.5000)
layout:setBottomMargin(-31.5000)
hall_room_fish_2_7:setBlendFunc({src = 1, dst = 771})
fish_1:addChild(hall_room_fish_2_7)

--Create hall_room_fish_5_effect_17
local hall_room_fish_5_effect_17 = cc.Sprite:create("hall/room/hall_room_fish_5_effect.png")
hall_room_fish_5_effect_17:setName("hall_room_fish_5_effect_17")
hall_room_fish_5_effect_17:setTag(71)
hall_room_fish_5_effect_17:setCascadeColorEnabled(true)
hall_room_fish_5_effect_17:setCascadeOpacityEnabled(true)
hall_room_fish_5_effect_17:setPosition(35.0159, 104.1657)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_fish_5_effect_17)
layout:setSize({width = 95.0000, height = 65.0000})
layout:setLeftMargin(-12.4841)
layout:setRightMargin(-82.5159)
layout:setTopMargin(-136.6657)
layout:setBottomMargin(71.6657)
hall_room_fish_5_effect_17:setBlendFunc({src = 770, dst = 1})
fish_1:addChild(hall_room_fish_5_effect_17)

--Create hall_room_fish_5_hand2_15
local hall_room_fish_5_hand2_15 = cc.Sprite:create("hall/room/hall_room_fish_5_hand2.png")
hall_room_fish_5_hand2_15:setName("hall_room_fish_5_hand2_15")
hall_room_fish_5_hand2_15:setTag(69)
hall_room_fish_5_hand2_15:setCascadeColorEnabled(true)
hall_room_fish_5_hand2_15:setCascadeOpacityEnabled(true)
hall_room_fish_5_hand2_15:setPosition(18.8354, 116.5345)
hall_room_fish_5_hand2_15:setScaleX(0.9000)
hall_room_fish_5_hand2_15:setScaleY(0.9000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_fish_5_hand2_15)
layout:setSize({width = 139.0000, height = 103.0000})
layout:setLeftMargin(-50.6646)
layout:setRightMargin(-88.3354)
layout:setTopMargin(-168.0345)
layout:setBottomMargin(65.0345)
hall_room_fish_5_hand2_15:setBlendFunc({src = 1, dst = 771})
fish_1:addChild(hall_room_fish_5_hand2_15)

--Create hall_room_fish_5_veins_1
local hall_room_fish_5_veins_1 = cc.Sprite:create("hall/room/hall_room_fish_5_veins.png")
hall_room_fish_5_veins_1:setName("hall_room_fish_5_veins_1")
hall_room_fish_5_veins_1:setTag(29)
hall_room_fish_5_veins_1:setCascadeColorEnabled(true)
hall_room_fish_5_veins_1:setCascadeOpacityEnabled(true)
hall_room_fish_5_veins_1:setPosition(42.8089, 212.4573)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_fish_5_veins_1)
layout:setSize({width = 40.0000, height = 39.0000})
layout:setLeftMargin(22.8089)
layout:setRightMargin(-62.8089)
layout:setTopMargin(-231.9573)
layout:setBottomMargin(192.9573)
hall_room_fish_5_veins_1:setBlendFunc({src = 1, dst = 771})
fish_1:addChild(hall_room_fish_5_veins_1)

--Create fish_2
local fish_2=cc.Node:create()
fish_2:setName("fish_2")
fish_2:setTag(425)
fish_2:setCascadeColorEnabled(true)
fish_2:setCascadeOpacityEnabled(true)
fish_2:setPosition(0.0000, 30.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(fish_2)
layout:setTopMargin(-30.0000)
layout:setBottomMargin(30.0000)
Node:addChild(fish_2)

--Create hall_room_fish_2_8
local hall_room_fish_2_8 = cc.Sprite:create("hall/room/hall_room_fish_4.png")
hall_room_fish_2_8:setName("hall_room_fish_2_8")
hall_room_fish_2_8:setTag(426)
hall_room_fish_2_8:setCascadeColorEnabled(true)
hall_room_fish_2_8:setCascadeOpacityEnabled(true)
hall_room_fish_2_8:setPosition(-46.0000, 20.0000)
hall_room_fish_2_8:setScaleX(0.9500)
hall_room_fish_2_8:setScaleY(0.8686)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_fish_2_8)
layout:setSize({width = 150.0000, height = 143.0000})
layout:setLeftMargin(-121.0000)
layout:setRightMargin(-29.0000)
layout:setTopMargin(-91.5000)
layout:setBottomMargin(-51.5000)
hall_room_fish_2_8:setBlendFunc({src = 1, dst = 771})
fish_2:addChild(hall_room_fish_2_8)

--Create hall_room_fish_4_hand_20
local hall_room_fish_4_hand_20 = cc.Sprite:create("hall/room/hall_room_fish_4_hand.png")
hall_room_fish_4_hand_20:setName("hall_room_fish_4_hand_20")
hall_room_fish_4_hand_20:setTag(74)
hall_room_fish_4_hand_20:setCascadeColorEnabled(true)
hall_room_fish_4_hand_20:setCascadeOpacityEnabled(true)
hall_room_fish_4_hand_20:setPosition(-71.9998, -26.0000)
hall_room_fish_4_hand_20:setScaleX(0.9000)
hall_room_fish_4_hand_20:setScaleY(0.9000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_fish_4_hand_20)
layout:setSize({width = 105.0000, height = 65.0000})
layout:setLeftMargin(-124.4998)
layout:setRightMargin(19.4998)
layout:setTopMargin(-6.5000)
layout:setBottomMargin(-58.5000)
hall_room_fish_4_hand_20:setBlendFunc({src = 1, dst = 771})
fish_2:addChild(hall_room_fish_4_hand_20)

--Create hall_room_fish_4_eyes1
local hall_room_fish_4_eyes1 = cc.Sprite:create("hall/room/hall_room_fish_4_eyes1.png")
hall_room_fish_4_eyes1:setName("hall_room_fish_4_eyes1")
hall_room_fish_4_eyes1:setTag(74)
hall_room_fish_4_eyes1:setCascadeColorEnabled(true)
hall_room_fish_4_eyes1:setCascadeOpacityEnabled(true)
hall_room_fish_4_eyes1:setPosition(-50.4590, 15.0950)
hall_room_fish_4_eyes1:setScaleX(0.9000)
hall_room_fish_4_eyes1:setScaleY(0.9000)
hall_room_fish_4_eyes1:setRotationSkewX(22.1623)
hall_room_fish_4_eyes1:setRotationSkewY(22.1623)
hall_room_fish_4_eyes1:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_fish_4_eyes1)
layout:setSize({width = 44.0000, height = 45.0000})
layout:setLeftMargin(-72.4590)
layout:setRightMargin(28.4590)
layout:setTopMargin(-37.5950)
layout:setBottomMargin(-7.4050)
hall_room_fish_4_eyes1:setBlendFunc({src = 1, dst = 771})
fish_2:addChild(hall_room_fish_4_eyes1)

--Create hall_room_fish_4_eyes2
local hall_room_fish_4_eyes2 = cc.Sprite:create("hall/room/hall_room_fish_4_eyes2.png")
hall_room_fish_4_eyes2:setName("hall_room_fish_4_eyes2")
hall_room_fish_4_eyes2:setTag(75)
hall_room_fish_4_eyes2:setCascadeColorEnabled(true)
hall_room_fish_4_eyes2:setCascadeOpacityEnabled(true)
hall_room_fish_4_eyes2:setPosition(-100.6463, 20.4401)
hall_room_fish_4_eyes2:setScaleX(0.9000)
hall_room_fish_4_eyes2:setScaleY(0.9000)
hall_room_fish_4_eyes2:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_fish_4_eyes2)
layout:setSize({width = 26.0000, height = 39.0000})
layout:setLeftMargin(-113.6463)
layout:setRightMargin(87.6463)
layout:setTopMargin(-39.9401)
layout:setBottomMargin(0.9401)
hall_room_fish_4_eyes2:setBlendFunc({src = 1, dst = 771})
fish_2:addChild(hall_room_fish_4_eyes2)

--Create title
local title=cc.Node:create()
title:setName("title")
title:setTag(80)
title:setCascadeColorEnabled(true)
title:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(title)
Node:addChild(title)

--Create hall_room_title_2_9
local hall_room_title_2_9 = cc.Sprite:create("hall/room/hall_room_title_4.png")
hall_room_title_2_9:setName("hall_room_title_2_9")
hall_room_title_2_9:setTag(79)
hall_room_title_2_9:setCascadeColorEnabled(true)
hall_room_title_2_9:setCascadeOpacityEnabled(true)
hall_room_title_2_9:setPosition(0.0000, -86.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_2_9)
layout:setSize({width = 212.0000, height = 96.0000})
layout:setLeftMargin(-106.0000)
layout:setRightMargin(-106.0000)
layout:setTopMargin(38.0000)
layout:setBottomMargin(-134.0000)
hall_room_title_2_9:setBlendFunc({src = 1, dst = 771})
title:addChild(hall_room_title_2_9)

--Create hall_room_title_light_3_14
local hall_room_title_light_3_14 = cc.Sprite:create("hall/room/hall_room_title_light_3.png")
hall_room_title_light_3_14:setName("hall_room_title_light_3_14")
hall_room_title_light_3_14:setTag(85)
hall_room_title_light_3_14:setCascadeColorEnabled(true)
hall_room_title_light_3_14:setCascadeOpacityEnabled(true)
hall_room_title_light_3_14:setPosition(98.0000, -43.3778)
hall_room_title_light_3_14:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_light_3_14)
layout:setSize({width = 50.0000, height = 50.0000})
layout:setLeftMargin(73.0000)
layout:setRightMargin(-123.0000)
layout:setTopMargin(18.3778)
layout:setBottomMargin(-68.3778)
hall_room_title_light_3_14:setBlendFunc({src = 1, dst = 1})
title:addChild(hall_room_title_light_3_14)

--Create run_light
local run_light = ccui.Layout:create()
run_light:ignoreContentAdaptWithSize(false)
run_light:setClippingEnabled(true)
run_light:setBackGroundColorOpacity(102)
run_light:setLayoutComponentEnabled(true)
run_light:setName("run_light")
run_light:setTag(86)
run_light:setCascadeColorEnabled(true)
run_light:setCascadeOpacityEnabled(true)
run_light:setPosition(-98.8494, -118.6861)
run_light:setScaleX(0.9600)
run_light:setScaleY(0.3025)
run_light:setRotationSkewX(7.9999)
run_light:setRotationSkewY(-3.9998)
layout = ccui.LayoutComponent:bindLayoutComponent(run_light)
layout:setSize({width = 200.0000, height = 200.0000})
layout:setLeftMargin(-98.8494)
layout:setRightMargin(-101.1506)
layout:setTopMargin(-81.3139)
layout:setBottomMargin(-118.6861)
title:addChild(run_light)

--Create hall_room_title_light_1_13
local hall_room_title_light_1_13 = cc.Sprite:create("hall/room/hall_room_title_light_1.png")
hall_room_title_light_1_13:setName("hall_room_title_light_1_13")
hall_room_title_light_1_13:setTag(84)
hall_room_title_light_1_13:setCascadeColorEnabled(true)
hall_room_title_light_1_13:setCascadeOpacityEnabled(true)
hall_room_title_light_1_13:setPosition(-32.4290, 97.2122)
hall_room_title_light_1_13:setScaleX(0.8000)
hall_room_title_light_1_13:setScaleY(2.4847)
hall_room_title_light_1_13:setRotationSkewX(-2.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_light_1_13)
layout:setPositionPercentX(-0.1621)
layout:setPositionPercentY(0.4861)
layout:setPercentWidth(0.4700)
layout:setPercentHeight(0.5200)
layout:setSize({width = 94.0000, height = 104.0000})
layout:setLeftMargin(-79.4290)
layout:setRightMargin(185.4290)
layout:setTopMargin(50.7878)
layout:setBottomMargin(45.2122)
hall_room_title_light_1_13:setBlendFunc({src = 774, dst = 1})
run_light:addChild(hall_room_title_light_1_13)

--Create hall_room_title_light_1_13_0
local hall_room_title_light_1_13_0 = cc.Sprite:create("hall/room/hall_room_title_light_1.png")
hall_room_title_light_1_13_0:setName("hall_room_title_light_1_13_0")
hall_room_title_light_1_13_0:setTag(96)
hall_room_title_light_1_13_0:setCascadeColorEnabled(true)
hall_room_title_light_1_13_0:setCascadeOpacityEnabled(true)
hall_room_title_light_1_13_0:setPosition(-32.4290, 97.2122)
hall_room_title_light_1_13_0:setScaleX(0.8000)
hall_room_title_light_1_13_0:setScaleY(2.4847)
hall_room_title_light_1_13_0:setRotationSkewX(-2.0000)
hall_room_title_light_1_13_0:setOpacity(127)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_light_1_13_0)
layout:setPositionPercentX(-0.1621)
layout:setPositionPercentY(0.4861)
layout:setPercentWidth(0.4700)
layout:setPercentHeight(0.5200)
layout:setSize({width = 94.0000, height = 104.0000})
layout:setLeftMargin(-79.4290)
layout:setRightMargin(185.4290)
layout:setTopMargin(50.7878)
layout:setBottomMargin(45.2122)
hall_room_title_light_1_13_0:setBlendFunc({src = 774, dst = 1})
run_light:addChild(hall_room_title_light_1_13_0)

--Create node_opentime
local node_opentime=cc.Node:create()
node_opentime:setName("node_opentime")
node_opentime:setTag(99)
node_opentime:setCascadeColorEnabled(true)
node_opentime:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(node_opentime)
Node:addChild(node_opentime)

--Create spr_open_1
local spr_open_1 = cc.Sprite:create("hall/room/hall_room_pic_kfsj.png")
spr_open_1:setName("spr_open_1")
spr_open_1:setTag(100)
spr_open_1:setCascadeColorEnabled(true)
spr_open_1:setCascadeOpacityEnabled(true)
spr_open_1:setPosition(0.0000, 9.7171)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_open_1)
layout:setPositionPercentXEnabled(true)
layout:setSize({width = 132.0000, height = 44.0000})
layout:setLeftMargin(-66.0000)
layout:setRightMargin(-66.0000)
layout:setTopMargin(-31.7171)
layout:setBottomMargin(-12.2829)
spr_open_1:setBlendFunc({src = 1, dst = 771})
node_opentime:addChild(spr_open_1)

--Create spr_timebg
local spr_timebg = ccui.ImageView:create()
spr_timebg:ignoreContentAdaptWithSize(false)
spr_timebg:loadTexture("battle/friend/friend_bg_1.png",0)
spr_timebg:setScale9Enabled(true)
spr_timebg:setCapInsets({x = 95, y = 1, width = 100, height = 1})
spr_timebg:setLayoutComponentEnabled(true)
spr_timebg:setName("spr_timebg")
spr_timebg:setTag(103)
spr_timebg:setCascadeColorEnabled(true)
spr_timebg:setCascadeOpacityEnabled(true)
spr_timebg:setPosition(66.0000, -17.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_timebg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(-0.3864)
layout:setPercentWidth(2.0455)
layout:setPercentHeight(0.7955)
layout:setSize({width = 270.0000, height = 35.0000})
layout:setLeftMargin(-69.0000)
layout:setRightMargin(-69.0000)
layout:setTopMargin(43.5000)
layout:setBottomMargin(-34.5000)
spr_open_1:addChild(spr_timebg)

--Create text_opentime
local text_opentime = ccui.Text:create()
text_opentime:ignoreContentAdaptWithSize(true)
text_opentime:setTextAreaSize({width = 0, height = 0})
text_opentime:setFontSize(32)
text_opentime:setString([[00.00-00.00]])
text_opentime:setTextHorizontalAlignment(1)
text_opentime:setTextVerticalAlignment(1)
text_opentime:setLayoutComponentEnabled(true)
text_opentime:setName("text_opentime")
text_opentime:setTag(102)
text_opentime:setCascadeColorEnabled(true)
text_opentime:setCascadeOpacityEnabled(true)
text_opentime:setPosition(66.0000, -17.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(text_opentime)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(-0.3864)
layout:setPercentWidth(1.3333)
layout:setPercentHeight(0.7500)
layout:setSize({width = 176.0000, height = 33.0000})
layout:setLeftMargin(-22.0000)
layout:setRightMargin(-22.0000)
layout:setTopMargin(44.5000)
layout:setBottomMargin(-33.5000)
spr_open_1:addChild(text_opentime)

--Create spr_open_0
local spr_open_0 = cc.Sprite:create("hall/room/hall_room_pic_zwkf.png")
spr_open_0:setName("spr_open_0")
spr_open_0:setTag(39)
spr_open_0:setCascadeColorEnabled(true)
spr_open_0:setCascadeOpacityEnabled(true)
spr_open_0:setPosition(0.0000, 9.7200)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_open_0)
layout:setPositionPercentXEnabled(true)
layout:setSize({width = 132.0000, height = 44.0000})
layout:setLeftMargin(-66.0000)
layout:setRightMargin(-66.0000)
layout:setTopMargin(-31.7200)
layout:setBottomMargin(-12.2800)
spr_open_0:setBlendFunc({src = 1, dst = 771})
node_opentime:addChild(spr_open_0)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(120)
result['animation']:setTimeSpeed(1.0000)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(7.0002)
localFrame:setY(-29.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(7.0002)
localFrame:setY(-25.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(7.0002)
localFrame:setY(-29.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_bgdown_4_3_1)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_bgdown_4_3_1)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_bgdown_4_3_1)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-66.5701)
localFrame:setY(-34.7644)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-66.5697)
localFrame:setY(-34.7644)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-66.5701)
localFrame:setY(-34.7644)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_bgdown_1)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_bgdown_1)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(-4.0386)
localFrame:setSkewY(-4.0376)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_bgdown_1)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(89.6188)
localFrame:setY(-23.7951)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(89.6188)
localFrame:setY(-23.7952)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(89.6188)
localFrame:setY(-23.7951)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_bgdown_2)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_bgdown_2)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(-14.1969)
localFrame:setSkewY(-14.1942)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(-9.5518)
localFrame:setSkewY(-9.5491)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(-14.1969)
localFrame:setSkewY(-14.1942)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_bgdown_2)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(light)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(light)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setX(0.0000)
localFrame:setY(5.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(bg)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(bg)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-80.0000)
localFrame:setY(122.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setX(-80.0000)
localFrame:setY(135.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-80.0000)
localFrame:setY(122.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_effect_1_2_4)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_effect_1_2_4)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(61.6201)
localFrame:setY(96.1639)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(60.4244)
localFrame:setY(98.5548)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(61.6201)
localFrame:setY(96.1639)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_fish_5_hand1_16)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_fish_5_hand1_16)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(-25.5324)
localFrame:setSkewY(-25.5325)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_fish_5_hand1_16)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setScaleX(0.9500)
localFrame:setScaleY(0.8686)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(4)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setScaleX(0.9500)
localFrame:setScaleY(0.8686)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_fish_2_7)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(27.0000)
localFrame:setY(100.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(4)
localFrame:setX(27.0000)
localFrame:setY(100.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_fish_2_7)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(35.0159)
localFrame:setY(104.1657)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(38.8596)
localFrame:setY(109.2912)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(35.0159)
localFrame:setY(104.1657)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_fish_5_effect_17)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_fish_5_effect_17)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_fish_5_effect_17)

--Create BlendFuncTimeline
local BlendFuncTimeline = ccs.Timeline:create()

result['animation']:addTimeline(BlendFuncTimeline)
BlendFuncTimeline:setNode(hall_room_fish_5_effect_17)

--Create FileDataTimeline
local FileDataTimeline = ccs.Timeline:create()

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(false)
localFrame:setTextureName("hall/room/hall_room_fish_5_effect.png")
FileDataTimeline:addFrame(localFrame)

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(false)
localFrame:setTextureName("hall/room/hall_room_fish_5_effect.png")
FileDataTimeline:addFrame(localFrame)

result['animation']:addTimeline(FileDataTimeline)
FileDataTimeline:setNode(hall_room_fish_5_effect_17)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(18.8354)
localFrame:setY(116.5345)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(22.8684)
localFrame:setY(116.7165)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(18.8354)
localFrame:setY(116.5345)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_fish_5_hand2_15)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_fish_5_hand2_15)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(-3.2596)
localFrame:setSkewY(-3.2598)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_fish_5_hand2_15)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(42.8089)
localFrame:setY(212.4573)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(42.8089)
localFrame:setY(212.4573)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(15)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(42.8089)
localFrame:setY(212.4573)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_fish_5_veins_1)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.7500)
localFrame:setScaleY(0.7500)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(15)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_fish_5_veins_1)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(15)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_fish_5_veins_1)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setX(0.0000)
localFrame:setY(17.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(fish_1)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(fish_1)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setScaleX(0.9500)
localFrame:setScaleY(0.8686)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(50)
localFrame:setTween(true)
localFrame:setTweenType(4)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setScaleX(0.9500)
localFrame:setScaleY(0.8686)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_fish_2_8)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(50)
localFrame:setTween(true)
localFrame:setTweenType(4)
localFrame:setX(-46.0000)
localFrame:setY(20.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_fish_2_8)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-71.9998)
localFrame:setY(-26.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(50)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-70.9997)
localFrame:setY(-25.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-71.9998)
localFrame:setY(-26.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_fish_4_hand_20)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(50)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.8500)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_fish_4_hand_20)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_fish_4_hand_20)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-50.4590)
localFrame:setY(15.0950)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(65)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-50.4590)
localFrame:setY(15.0950)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-50.4590)
localFrame:setY(15.0950)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(75)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-50.4590)
localFrame:setY(15.0950)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_fish_4_eyes1)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(65)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(75)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_fish_4_eyes1)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(22.1623)
localFrame:setSkewY(22.1623)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(65)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(22.1623)
localFrame:setSkewY(22.1623)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(22.1623)
localFrame:setSkewY(22.1623)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(75)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(22.1623)
localFrame:setSkewY(22.1623)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_fish_4_eyes1)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(65)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(75)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(hall_room_fish_4_eyes1)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-100.6463)
localFrame:setY(20.4401)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(65)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-100.6463)
localFrame:setY(20.4401)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-100.6463)
localFrame:setY(20.4401)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(75)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-100.6463)
localFrame:setY(20.4401)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_fish_4_eyes2)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(65)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(75)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.9000)
localFrame:setScaleY(0.9000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_fish_4_eyes2)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(65)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(75)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_fish_4_eyes2)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(65)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(70)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(75)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(hall_room_fish_4_eyes2)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setX(0.0000)
localFrame:setY(30.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(50)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setX(0.0000)
localFrame:setY(45.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setX(0.0000)
localFrame:setY(30.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(fish_2)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(50)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(fish_2)

--Create FileDataTimeline
local FileDataTimeline = ccs.Timeline:create()

localFrame = ccs.TextureFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(false)
localFrame:setTextureName("hall/room/hall_room_title_4.png")
FileDataTimeline:addFrame(localFrame)

result['animation']:addTimeline(FileDataTimeline)
FileDataTimeline:setNode(hall_room_title_2_9)

--Create BlendFuncTimeline
local BlendFuncTimeline = ccs.Timeline:create()

result['animation']:addTimeline(BlendFuncTimeline)
BlendFuncTimeline:setNode(hall_room_title_2_9)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(98.0000)
localFrame:setY(-43.3778)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(98.0000)
localFrame:setY(-45.1882)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_title_light_3_14)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_title_light_3_14)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(520.0000)
localFrame:setSkewY(520.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_title_light_3_14)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(55)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(80)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(hall_room_title_light_3_14)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(13)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-32.4290)
localFrame:setY(97.2122)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(40)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(232.1451)
localFrame:setY(90.7435)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_title_light_1_13)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(21)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-32.4290)
localFrame:setY(97.2122)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(48)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(232.1451)
localFrame:setY(90.7435)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_title_light_1_13_0)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(50)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setX(0.0000)
localFrame:setY(4.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(title)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(50)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(7.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(node_opentime)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(50)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(node_opentime)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(50)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(node_opentime)
--Create Animation List
local roomact = {name="roomact", startIndex=0, endIndex=120}
result['animation']:addAnimationInfo(roomact)
local stopact = {name="stopact", startIndex=0, endIndex=1}
result['animation']:addAnimationInfo(stopact)

result['root'] = Node
return result;
end

return Result

