--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create bg
local bg=cc.Node:create()
bg:setName("bg")
bg:setTag(69)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
Node:addChild(bg)

--Create hall_room_bg_2_2
local hall_room_bg_2_2 = cc.Sprite:create("hall/room/hall_room_bg_2.png")
hall_room_bg_2_2:setName("hall_room_bg_2_2")
hall_room_bg_2_2:setTag(71)
hall_room_bg_2_2:setCascadeColorEnabled(true)
hall_room_bg_2_2:setCascadeOpacityEnabled(true)
hall_room_bg_2_2:setPosition(0.0000, 30.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_bg_2_2)
layout:setSize({width = 326.0000, height = 326.0000})
layout:setLeftMargin(-163.0000)
layout:setRightMargin(-163.0000)
layout:setTopMargin(-193.0000)
layout:setBottomMargin(-133.0000)
hall_room_bg_2_2:setBlendFunc({src = 1, dst = 771})
bg:addChild(hall_room_bg_2_2)

--Create hall_room_ground_8
local hall_room_ground_8 = cc.Sprite:create("hall/room/hall_room_ground.png")
hall_room_ground_8:setName("hall_room_ground_8")
hall_room_ground_8:setTag(78)
hall_room_ground_8:setCascadeColorEnabled(true)
hall_room_ground_8:setCascadeOpacityEnabled(true)
hall_room_ground_8:setAnchorPoint(1.0000, 0.5000)
hall_room_ground_8:setPosition(0.0000, -76.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_ground_8)
layout:setSize({width = 162.0000, height = 210.0000})
layout:setLeftMargin(-162.0000)
layout:setTopMargin(-29.0000)
layout:setBottomMargin(-181.0000)
hall_room_ground_8:setBlendFunc({src = 1, dst = 771})
bg:addChild(hall_room_ground_8)

--Create hall_room_ground_8_0
local hall_room_ground_8_0 = cc.Sprite:create("hall/room/hall_room_ground.png")
hall_room_ground_8_0:setName("hall_room_ground_8_0")
hall_room_ground_8_0:setTag(90)
hall_room_ground_8_0:setCascadeColorEnabled(true)
hall_room_ground_8_0:setCascadeOpacityEnabled(true)
hall_room_ground_8_0:setAnchorPoint(0.0000, 0.5000)
hall_room_ground_8_0:setPosition(0.0000, -76.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_ground_8_0)
layout:setSize({width = 162.0000, height = 210.0000})
layout:setRightMargin(-162.0000)
layout:setTopMargin(-29.0000)
layout:setBottomMargin(-181.0000)
hall_room_ground_8_0:setFlippedX(true)
hall_room_ground_8_0:setBlendFunc({src = 1, dst = 771})
bg:addChild(hall_room_ground_8_0)

--Create hall_room_bgdown_2_1
local hall_room_bgdown_2_1 = cc.Sprite:create("hall/room/hall_room_bgdown_2.png")
hall_room_bgdown_2_1:setName("hall_room_bgdown_2_1")
hall_room_bgdown_2_1:setTag(70)
hall_room_bgdown_2_1:setCascadeColorEnabled(true)
hall_room_bgdown_2_1:setCascadeOpacityEnabled(true)
hall_room_bgdown_2_1:setPosition(7.0000, 18.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_bgdown_2_1)
layout:setSize({width = 336.0000, height = 186.0000})
layout:setLeftMargin(-161.0000)
layout:setRightMargin(-175.0000)
layout:setTopMargin(-111.0000)
layout:setBottomMargin(-75.0000)
hall_room_bgdown_2_1:setBlendFunc({src = 1, dst = 771})
bg:addChild(hall_room_bgdown_2_1)

--Create spr_word_room
local spr_word_room = cc.Sprite:create("hall/room/title/room_title_2_1.png")
spr_word_room:setName("spr_word_room")
spr_word_room:setTag(87)
spr_word_room:setCascadeColorEnabled(true)
spr_word_room:setCascadeOpacityEnabled(true)
spr_word_room:setPosition(0.0000, -148.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_word_room)
layout:setSize({width = 132.0000, height = 35.0000})
layout:setLeftMargin(-66.0000)
layout:setRightMargin(-66.0000)
layout:setTopMargin(131.0000)
layout:setBottomMargin(-166.0000)
spr_word_room:setBlendFunc({src = 1, dst = 771})
bg:addChild(spr_word_room)

--Create light
local light=cc.Node:create()
light:setName("light")
light:setTag(94)
light:setCascadeColorEnabled(true)
light:setCascadeOpacityEnabled(true)
light:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(light)
bg:addChild(light)

--Create hall_room_title_pb_light_16
local hall_room_title_pb_light_16 = cc.Sprite:create("hall/room/hall_room_title_pb_light.png")
hall_room_title_pb_light_16:setName("hall_room_title_pb_light_16")
hall_room_title_pb_light_16:setTag(88)
hall_room_title_pb_light_16:setCascadeColorEnabled(true)
hall_room_title_pb_light_16:setCascadeOpacityEnabled(true)
hall_room_title_pb_light_16:setPosition(-72.0000, -149.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_pb_light_16)
layout:setSize({width = 16.0000, height = 24.0000})
layout:setLeftMargin(-80.0000)
layout:setRightMargin(64.0000)
layout:setTopMargin(137.0000)
layout:setBottomMargin(-161.0000)
hall_room_title_pb_light_16:setBlendFunc({src = 1, dst = 771})
light:addChild(hall_room_title_pb_light_16)

--Create hall_room_title_pb_light_16_0
local hall_room_title_pb_light_16_0 = cc.Sprite:create("hall/room/hall_room_title_pb_light.png")
hall_room_title_pb_light_16_0:setName("hall_room_title_pb_light_16_0")
hall_room_title_pb_light_16_0:setTag(91)
hall_room_title_pb_light_16_0:setCascadeColorEnabled(true)
hall_room_title_pb_light_16_0:setCascadeOpacityEnabled(true)
hall_room_title_pb_light_16_0:setPosition(72.0000, -149.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_pb_light_16_0)
layout:setSize({width = 16.0000, height = 24.0000})
layout:setLeftMargin(64.0000)
layout:setRightMargin(-80.0000)
layout:setTopMargin(137.0000)
layout:setBottomMargin(-161.0000)
hall_room_title_pb_light_16_0:setFlippedX(true)
hall_room_title_pb_light_16_0:setBlendFunc({src = 1, dst = 771})
light:addChild(hall_room_title_pb_light_16_0)

--Create hall_pic_room_locked_1
local hall_pic_room_locked_1 = cc.Sprite:create("hall/hallpic/hall_pic_room_locked.png")
hall_pic_room_locked_1:setName("hall_pic_room_locked_1")
hall_pic_room_locked_1:setTag(25)
hall_pic_room_locked_1:setCascadeColorEnabled(true)
hall_pic_room_locked_1:setCascadeOpacityEnabled(true)
hall_pic_room_locked_1:setPosition(85.0000, -145.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_pic_room_locked_1)
layout:setSize({width = 38.0000, height = 40.0000})
layout:setLeftMargin(66.0000)
layout:setRightMargin(-104.0000)
layout:setTopMargin(125.0000)
layout:setBottomMargin(-165.0000)
hall_pic_room_locked_1:setBlendFunc({src = 1, dst = 771})
bg:addChild(hall_pic_room_locked_1)

--Create fish
local fish=cc.Node:create()
fish:setName("fish")
fish:setTag(93)
fish:setCascadeColorEnabled(true)
fish:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(fish)
Node:addChild(fish)

--Create hall_room_fish_2_7
local hall_room_fish_2_7 = cc.Sprite:create("hall/room/hall_room_fish_2.png")
hall_room_fish_2_7:setName("hall_room_fish_2_7")
hall_room_fish_2_7:setTag(77)
hall_room_fish_2_7:setCascadeColorEnabled(true)
hall_room_fish_2_7:setCascadeOpacityEnabled(true)
hall_room_fish_2_7:setPosition(-2.5809, 67.4700)
hall_room_fish_2_7:setScaleX(1.0200)
hall_room_fish_2_7:setScaleY(0.9500)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_fish_2_7)
layout:setSize({width = 292.0000, height = 328.0000})
layout:setLeftMargin(-148.5809)
layout:setRightMargin(-143.4191)
layout:setTopMargin(-231.4700)
layout:setBottomMargin(-96.5300)
hall_room_fish_2_7:setBlendFunc({src = 1, dst = 771})
fish:addChild(hall_room_fish_2_7)

--Create hall_room_fish_1_eyes_20
local hall_room_fish_1_eyes_20 = cc.Sprite:create("hall/room/hall_room_fish_1_eyes.png")
hall_room_fish_1_eyes_20:setName("hall_room_fish_1_eyes_20")
hall_room_fish_1_eyes_20:setTag(95)
hall_room_fish_1_eyes_20:setCascadeColorEnabled(true)
hall_room_fish_1_eyes_20:setCascadeOpacityEnabled(true)
hall_room_fish_1_eyes_20:setPosition(-16.0000, 165.0000)
hall_room_fish_1_eyes_20:setScaleX(0.5000)
hall_room_fish_1_eyes_20:setScaleY(0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_fish_1_eyes_20)
layout:setSize({width = 14.0000, height = 14.0000})
layout:setLeftMargin(-23.0000)
layout:setRightMargin(9.0000)
layout:setTopMargin(-172.0000)
layout:setBottomMargin(158.0000)
hall_room_fish_1_eyes_20:setBlendFunc({src = 1, dst = 771})
fish:addChild(hall_room_fish_1_eyes_20)

--Create room_effect
local room_effect=cc.Node:create()
room_effect:setName("room_effect")
room_effect:setTag(76)
room_effect:setCascadeColorEnabled(true)
room_effect:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(room_effect)
Node:addChild(room_effect)

--Create hall_room_effect_2_1_3
local hall_room_effect_2_1_3 = cc.Sprite:create("hall/room/hall_room_effect_2_1.png")
hall_room_effect_2_1_3:setName("hall_room_effect_2_1_3")
hall_room_effect_2_1_3:setTag(72)
hall_room_effect_2_1_3:setCascadeColorEnabled(true)
hall_room_effect_2_1_3:setCascadeOpacityEnabled(true)
hall_room_effect_2_1_3:setPosition(-139.0000, 44.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_effect_2_1_3)
layout:setSize({width = 54.0000, height = 32.0000})
layout:setLeftMargin(-166.0000)
layout:setRightMargin(112.0000)
layout:setTopMargin(-60.0000)
layout:setBottomMargin(28.0000)
hall_room_effect_2_1_3:setBlendFunc({src = 1, dst = 771})
room_effect:addChild(hall_room_effect_2_1_3)

--Create hall_room_effect_2_2_4
local hall_room_effect_2_2_4 = cc.Sprite:create("hall/room/hall_room_effect_2_2.png")
hall_room_effect_2_2_4:setName("hall_room_effect_2_2_4")
hall_room_effect_2_2_4:setTag(73)
hall_room_effect_2_2_4:setCascadeColorEnabled(true)
hall_room_effect_2_2_4:setCascadeOpacityEnabled(true)
hall_room_effect_2_2_4:setPosition(-112.0000, 123.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_effect_2_2_4)
layout:setSize({width = 56.0000, height = 66.0000})
layout:setLeftMargin(-140.0000)
layout:setRightMargin(84.0000)
layout:setTopMargin(-156.0000)
layout:setBottomMargin(90.0000)
hall_room_effect_2_2_4:setBlendFunc({src = 1, dst = 771})
room_effect:addChild(hall_room_effect_2_2_4)

--Create hall_room_effect_2_3_5
local hall_room_effect_2_3_5 = cc.Sprite:create("hall/room/hall_room_effect_2_3.png")
hall_room_effect_2_3_5:setName("hall_room_effect_2_3_5")
hall_room_effect_2_3_5:setTag(74)
hall_room_effect_2_3_5:setCascadeColorEnabled(true)
hall_room_effect_2_3_5:setCascadeOpacityEnabled(true)
hall_room_effect_2_3_5:setPosition(140.0000, 25.8017)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_effect_2_3_5)
layout:setSize({width = 40.0000, height = 26.0000})
layout:setLeftMargin(120.0000)
layout:setRightMargin(-160.0000)
layout:setTopMargin(-38.8017)
layout:setBottomMargin(12.8017)
hall_room_effect_2_3_5:setBlendFunc({src = 1, dst = 771})
room_effect:addChild(hall_room_effect_2_3_5)

--Create hall_room_effect_2_4_6
local hall_room_effect_2_4_6 = cc.Sprite:create("hall/room/hall_room_effect_2_4.png")
hall_room_effect_2_4_6:setName("hall_room_effect_2_4_6")
hall_room_effect_2_4_6:setTag(75)
hall_room_effect_2_4_6:setCascadeColorEnabled(true)
hall_room_effect_2_4_6:setCascadeOpacityEnabled(true)
hall_room_effect_2_4_6:setPosition(144.0000, 143.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_effect_2_4_6)
layout:setSize({width = 46.0000, height = 54.0000})
layout:setLeftMargin(121.0000)
layout:setRightMargin(-167.0000)
layout:setTopMargin(-170.0000)
layout:setBottomMargin(116.0000)
hall_room_effect_2_4_6:setBlendFunc({src = 1, dst = 771})
room_effect:addChild(hall_room_effect_2_4_6)

--Create title
local title=cc.Node:create()
title:setName("title")
title:setTag(80)
title:setCascadeColorEnabled(true)
title:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(title)
Node:addChild(title)

--Create hall_room_title_2_9
local hall_room_title_2_9 = cc.Sprite:create("hall/room/hall_room_title_2.png")
hall_room_title_2_9:setName("hall_room_title_2_9")
hall_room_title_2_9:setTag(79)
hall_room_title_2_9:setCascadeColorEnabled(true)
hall_room_title_2_9:setCascadeOpacityEnabled(true)
hall_room_title_2_9:setPosition(0.0000, -86.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_2_9)
layout:setSize({width = 278.0000, height = 100.0000})
layout:setLeftMargin(-139.0000)
layout:setRightMargin(-139.0000)
layout:setTopMargin(36.0000)
layout:setBottomMargin(-136.0000)
hall_room_title_2_9:setBlendFunc({src = 1, dst = 771})
title:addChild(hall_room_title_2_9)

--Create hall_room_title_light_3_14
local hall_room_title_light_3_14 = cc.Sprite:create("hall/room/hall_room_title_light_3.png")
hall_room_title_light_3_14:setName("hall_room_title_light_3_14")
hall_room_title_light_3_14:setTag(85)
hall_room_title_light_3_14:setCascadeColorEnabled(true)
hall_room_title_light_3_14:setCascadeOpacityEnabled(true)
hall_room_title_light_3_14:setPosition(128.4567, -43.3778)
hall_room_title_light_3_14:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_light_3_14)
layout:setSize({width = 50.0000, height = 50.0000})
layout:setLeftMargin(103.4567)
layout:setRightMargin(-153.4567)
layout:setTopMargin(18.3778)
layout:setBottomMargin(-68.3778)
hall_room_title_light_3_14:setBlendFunc({src = 1, dst = 1})
title:addChild(hall_room_title_light_3_14)

--Create run_light
local run_light = ccui.Layout:create()
run_light:ignoreContentAdaptWithSize(false)
run_light:setClippingEnabled(true)
run_light:setBackGroundColorOpacity(102)
run_light:setLayoutComponentEnabled(true)
run_light:setName("run_light")
run_light:setTag(86)
run_light:setCascadeColorEnabled(true)
run_light:setCascadeOpacityEnabled(true)
run_light:setPosition(-130.7661, -119.5507)
run_light:setScaleX(1.2800)
run_light:setScaleY(0.3025)
run_light:setRotationSkewX(5.9993)
run_light:setRotationSkewY(-4.0006)
layout = ccui.LayoutComponent:bindLayoutComponent(run_light)
layout:setSize({width = 200.0000, height = 200.0000})
layout:setLeftMargin(-130.7661)
layout:setRightMargin(-69.2339)
layout:setTopMargin(-80.4493)
layout:setBottomMargin(-119.5507)
title:addChild(run_light)

--Create hall_room_title_light_1_13
local hall_room_title_light_1_13 = cc.Sprite:create("hall/room/hall_room_title_light_1.png")
hall_room_title_light_1_13:setName("hall_room_title_light_1_13")
hall_room_title_light_1_13:setTag(84)
hall_room_title_light_1_13:setCascadeColorEnabled(true)
hall_room_title_light_1_13:setCascadeOpacityEnabled(true)
hall_room_title_light_1_13:setPosition(-32.4290, 97.2122)
hall_room_title_light_1_13:setScaleX(0.8000)
hall_room_title_light_1_13:setScaleY(2.4847)
hall_room_title_light_1_13:setRotationSkewX(-2.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_light_1_13)
layout:setPositionPercentX(-0.1621)
layout:setPositionPercentY(0.4861)
layout:setPercentWidth(0.4700)
layout:setPercentHeight(0.5200)
layout:setSize({width = 94.0000, height = 104.0000})
layout:setLeftMargin(-79.4290)
layout:setRightMargin(185.4290)
layout:setTopMargin(50.7878)
layout:setBottomMargin(45.2122)
hall_room_title_light_1_13:setBlendFunc({src = 774, dst = 1})
run_light:addChild(hall_room_title_light_1_13)

--Create hall_room_title_light_1_13_0
local hall_room_title_light_1_13_0 = cc.Sprite:create("hall/room/hall_room_title_light_1.png")
hall_room_title_light_1_13_0:setName("hall_room_title_light_1_13_0")
hall_room_title_light_1_13_0:setTag(96)
hall_room_title_light_1_13_0:setCascadeColorEnabled(true)
hall_room_title_light_1_13_0:setCascadeOpacityEnabled(true)
hall_room_title_light_1_13_0:setPosition(-32.4290, 97.2122)
hall_room_title_light_1_13_0:setScaleX(0.8000)
hall_room_title_light_1_13_0:setScaleY(2.4847)
hall_room_title_light_1_13_0:setRotationSkewX(-2.0000)
hall_room_title_light_1_13_0:setOpacity(127)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_light_1_13_0)
layout:setPositionPercentX(-0.1621)
layout:setPositionPercentY(0.4861)
layout:setPercentWidth(0.4700)
layout:setPercentHeight(0.5200)
layout:setSize({width = 94.0000, height = 104.0000})
layout:setLeftMargin(-79.4290)
layout:setRightMargin(185.4290)
layout:setTopMargin(50.7878)
layout:setBottomMargin(45.2122)
hall_room_title_light_1_13_0:setBlendFunc({src = 774, dst = 1})
run_light:addChild(hall_room_title_light_1_13_0)

--Create node_unlocked
innerCSD = require("ui.hall.room.uiroom_unlocked")
innerProject = innerCSD.create(callBackProvider)
local node_unlocked = innerProject.root
node_unlocked.animation = innerProject.animation
node_unlocked:setName("node_unlocked")
node_unlocked:setTag(37)
node_unlocked:setCascadeColorEnabled(true)
node_unlocked:setCascadeOpacityEnabled(true)
node_unlocked:setPosition(85.0000, -145.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_unlocked)
layout:setLeftMargin(85.0000)
layout:setRightMargin(-85.0000)
layout:setTopMargin(145.0000)
layout:setBottomMargin(-145.0000)
innerProject.animation:setTimeSpeed(1.0000)
node_unlocked:runAction(innerProject.animation)
Node:addChild(node_unlocked)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(120)
result['animation']:setTimeSpeed(1.0000)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(light)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(light)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setX(0.0000)
localFrame:setY(5.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(bg)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(bg)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0200)
localFrame:setScaleY(0.9500)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0200)
localFrame:setScaleY(0.9500)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_fish_2_7)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setX(-16.0000)
localFrame:setY(165.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(6)
localFrame:setX(-17.5999)
localFrame:setY(167.3999)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setX(-16.0000)
localFrame:setY(165.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_fish_1_eyes_20)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setScaleX(0.5000)
localFrame:setScaleY(0.5000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setScaleX(0.5000)
localFrame:setScaleY(0.5000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_fish_1_eyes_20)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setX(0.0000)
localFrame:setY(20.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(fish)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(fish)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-139.0000)
localFrame:setY(44.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(71)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-139.9379)
localFrame:setY(30.8628)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-139.0000)
localFrame:setY(44.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_effect_2_1_3)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_effect_2_1_3)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_effect_2_1_3)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-112.0000)
localFrame:setY(123.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(71)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-113.8753)
localFrame:setY(147.3968)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-112.0000)
localFrame:setY(123.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_effect_2_2_4)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_effect_2_2_4)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_effect_2_2_4)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(140.0000)
localFrame:setY(25.8017)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(71)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(140.0000)
localFrame:setY(39.8772)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(140.0000)
localFrame:setY(25.8017)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_effect_2_3_5)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_effect_2_3_5)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_effect_2_3_5)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(144.0000)
localFrame:setY(143.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(71)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(146.8158)
localFrame:setY(158.0129)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(144.0000)
localFrame:setY(143.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_effect_2_4_6)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_effect_2_4_6)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_effect_2_4_6)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(128.4567)
localFrame:setY(-43.3778)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(129.0602)
localFrame:setY(-45.1882)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_title_light_3_14)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_title_light_3_14)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(520.0000)
localFrame:setSkewY(520.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_title_light_3_14)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(55)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(80)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(hall_room_title_light_3_14)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(13)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-32.4290)
localFrame:setY(97.2122)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(40)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(232.1451)
localFrame:setY(90.7435)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_title_light_1_13)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(21)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-32.4290)
localFrame:setY(97.2122)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(48)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(232.1451)
localFrame:setY(90.7435)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_title_light_1_13_0)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(4.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(title)
--Create Animation List
local roomact = {name="roomact", startIndex=0, endIndex=120}
result['animation']:addAnimationInfo(roomact)
local stopact = {name="stopact", startIndex=0, endIndex=1}
result['animation']:addAnimationInfo(stopact)

result['root'] = Node
return result;
end

return Result

