--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create bg
local bg=cc.Node:create()
bg:setName("bg")
bg:setTag(69)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
Node:addChild(bg)

--Create hall_room_bg_2_2
local hall_room_bg_2_2 = cc.Sprite:create("hall/room/hall_room_bg_3.png")
hall_room_bg_2_2:setName("hall_room_bg_2_2")
hall_room_bg_2_2:setTag(71)
hall_room_bg_2_2:setCascadeColorEnabled(true)
hall_room_bg_2_2:setCascadeOpacityEnabled(true)
hall_room_bg_2_2:setPosition(0.0000, 30.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_bg_2_2)
layout:setSize({width = 326.0000, height = 326.0000})
layout:setLeftMargin(-163.0000)
layout:setRightMargin(-163.0000)
layout:setTopMargin(-193.0000)
layout:setBottomMargin(-133.0000)
hall_room_bg_2_2:setBlendFunc({src = 1, dst = 771})
bg:addChild(hall_room_bg_2_2)

--Create hall_room_ground_8
local hall_room_ground_8 = cc.Sprite:create("hall/room/hall_room_ground.png")
hall_room_ground_8:setName("hall_room_ground_8")
hall_room_ground_8:setTag(78)
hall_room_ground_8:setCascadeColorEnabled(true)
hall_room_ground_8:setCascadeOpacityEnabled(true)
hall_room_ground_8:setAnchorPoint(1.0000, 0.5000)
hall_room_ground_8:setPosition(0.0000, -76.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_ground_8)
layout:setSize({width = 162.0000, height = 210.0000})
layout:setLeftMargin(-162.0000)
layout:setTopMargin(-29.0000)
layout:setBottomMargin(-181.0000)
hall_room_ground_8:setBlendFunc({src = 1, dst = 771})
bg:addChild(hall_room_ground_8)

--Create hall_room_ground_8_0
local hall_room_ground_8_0 = cc.Sprite:create("hall/room/hall_room_ground.png")
hall_room_ground_8_0:setName("hall_room_ground_8_0")
hall_room_ground_8_0:setTag(90)
hall_room_ground_8_0:setCascadeColorEnabled(true)
hall_room_ground_8_0:setCascadeOpacityEnabled(true)
hall_room_ground_8_0:setAnchorPoint(0.0000, 0.5000)
hall_room_ground_8_0:setPosition(0.0000, -76.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_ground_8_0)
layout:setSize({width = 162.0000, height = 210.0000})
layout:setRightMargin(-162.0000)
layout:setTopMargin(-29.0000)
layout:setBottomMargin(-181.0000)
hall_room_ground_8_0:setFlippedX(true)
hall_room_ground_8_0:setBlendFunc({src = 1, dst = 771})
bg:addChild(hall_room_ground_8_0)

--Create hall_room_bgdown_2_1
local hall_room_bgdown_2_1 = cc.Sprite:create("hall/room/hall_room_bgdown_3.png")
hall_room_bgdown_2_1:setName("hall_room_bgdown_2_1")
hall_room_bgdown_2_1:setTag(70)
hall_room_bgdown_2_1:setCascadeColorEnabled(true)
hall_room_bgdown_2_1:setCascadeOpacityEnabled(true)
hall_room_bgdown_2_1:setPosition(7.0000, 18.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_bgdown_2_1)
layout:setSize({width = 336.0000, height = 186.0000})
layout:setLeftMargin(-161.0000)
layout:setRightMargin(-175.0000)
layout:setTopMargin(-111.0000)
layout:setBottomMargin(-75.0000)
hall_room_bgdown_2_1:setBlendFunc({src = 1, dst = 771})
bg:addChild(hall_room_bgdown_2_1)

--Create spr_word_room
local spr_word_room = cc.Sprite:create("hall/room/title/room_title_3_1.png")
spr_word_room:setName("spr_word_room")
spr_word_room:setTag(87)
spr_word_room:setCascadeColorEnabled(true)
spr_word_room:setCascadeOpacityEnabled(true)
spr_word_room:setPosition(0.0000, -148.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_word_room)
layout:setSize({width = 132.0000, height = 35.0000})
layout:setLeftMargin(-66.0000)
layout:setRightMargin(-66.0000)
layout:setTopMargin(131.0000)
layout:setBottomMargin(-166.0000)
spr_word_room:setBlendFunc({src = 1, dst = 771})
bg:addChild(spr_word_room)

--Create light
local light=cc.Node:create()
light:setName("light")
light:setTag(94)
light:setCascadeColorEnabled(true)
light:setCascadeOpacityEnabled(true)
light:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(light)
bg:addChild(light)

--Create hall_room_title_pb_light_16
local hall_room_title_pb_light_16 = cc.Sprite:create("hall/room/hall_room_title_pb_light.png")
hall_room_title_pb_light_16:setName("hall_room_title_pb_light_16")
hall_room_title_pb_light_16:setTag(88)
hall_room_title_pb_light_16:setCascadeColorEnabled(true)
hall_room_title_pb_light_16:setCascadeOpacityEnabled(true)
hall_room_title_pb_light_16:setPosition(-72.0000, -149.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_pb_light_16)
layout:setSize({width = 16.0000, height = 24.0000})
layout:setLeftMargin(-80.0000)
layout:setRightMargin(64.0000)
layout:setTopMargin(137.0000)
layout:setBottomMargin(-161.0000)
hall_room_title_pb_light_16:setBlendFunc({src = 1, dst = 771})
light:addChild(hall_room_title_pb_light_16)

--Create hall_room_title_pb_light_16_0
local hall_room_title_pb_light_16_0 = cc.Sprite:create("hall/room/hall_room_title_pb_light.png")
hall_room_title_pb_light_16_0:setName("hall_room_title_pb_light_16_0")
hall_room_title_pb_light_16_0:setTag(91)
hall_room_title_pb_light_16_0:setCascadeColorEnabled(true)
hall_room_title_pb_light_16_0:setCascadeOpacityEnabled(true)
hall_room_title_pb_light_16_0:setPosition(72.0000, -149.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_pb_light_16_0)
layout:setSize({width = 16.0000, height = 24.0000})
layout:setLeftMargin(64.0000)
layout:setRightMargin(-80.0000)
layout:setTopMargin(137.0000)
layout:setBottomMargin(-161.0000)
hall_room_title_pb_light_16_0:setFlippedX(true)
hall_room_title_pb_light_16_0:setBlendFunc({src = 1, dst = 771})
light:addChild(hall_room_title_pb_light_16_0)

--Create hall_pic_room_locked_1
local hall_pic_room_locked_1 = cc.Sprite:create("hall/hallpic/hall_pic_room_locked.png")
hall_pic_room_locked_1:setName("hall_pic_room_locked_1")
hall_pic_room_locked_1:setTag(55)
hall_pic_room_locked_1:setCascadeColorEnabled(true)
hall_pic_room_locked_1:setCascadeOpacityEnabled(true)
hall_pic_room_locked_1:setPosition(85.0000, -145.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_pic_room_locked_1)
layout:setSize({width = 38.0000, height = 40.0000})
layout:setLeftMargin(66.0000)
layout:setRightMargin(-104.0000)
layout:setTopMargin(125.0000)
layout:setBottomMargin(-165.0000)
hall_pic_room_locked_1:setBlendFunc({src = 1, dst = 771})
bg:addChild(hall_pic_room_locked_1)

--Create fish
local fish=cc.Node:create()
fish:setName("fish")
fish:setTag(93)
fish:setCascadeColorEnabled(true)
fish:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(fish)
Node:addChild(fish)

--Create hall_room_fish_2_7
local hall_room_fish_2_7 = cc.Sprite:create("hall/room/hall_room_fish_3.png")
hall_room_fish_2_7:setName("hall_room_fish_2_7")
hall_room_fish_2_7:setTag(77)
hall_room_fish_2_7:setCascadeColorEnabled(true)
hall_room_fish_2_7:setCascadeOpacityEnabled(true)
hall_room_fish_2_7:setPosition(-2.5809, 67.4700)
hall_room_fish_2_7:setScaleX(1.0200)
hall_room_fish_2_7:setScaleY(0.9500)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_fish_2_7)
layout:setSize({width = 292.0000, height = 328.0000})
layout:setLeftMargin(-148.5809)
layout:setRightMargin(-143.4191)
layout:setTopMargin(-231.4700)
layout:setBottomMargin(-96.5300)
hall_room_fish_2_7:setBlendFunc({src = 1, dst = 771})
fish:addChild(hall_room_fish_2_7)

--Create fish_eye
local fish_eye=cc.Node:create()
fish_eye:setName("fish_eye")
fish_eye:setTag(125)
fish_eye:setCascadeColorEnabled(true)
fish_eye:setCascadeOpacityEnabled(true)
fish_eye:setPosition(7.7800, 119.3200)
layout = ccui.LayoutComponent:bindLayoutComponent(fish_eye)
layout:setLeftMargin(7.7800)
layout:setRightMargin(-7.7800)
layout:setTopMargin(-119.3200)
layout:setBottomMargin(119.3200)
fish:addChild(fish_eye)

--Create hall_room_fish_1_eyes_20
local hall_room_fish_1_eyes_20 = cc.Sprite:create("hall/room/hall_room_fish_1_eyes.png")
hall_room_fish_1_eyes_20:setName("hall_room_fish_1_eyes_20")
hall_room_fish_1_eyes_20:setTag(95)
hall_room_fish_1_eyes_20:setCascadeColorEnabled(true)
hall_room_fish_1_eyes_20:setCascadeOpacityEnabled(true)
hall_room_fish_1_eyes_20:setPosition(-36.0000, 1.0000)
hall_room_fish_1_eyes_20:setScaleX(0.3000)
hall_room_fish_1_eyes_20:setScaleY(0.3000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_fish_1_eyes_20)
layout:setSize({width = 14.0000, height = 14.0000})
layout:setLeftMargin(-43.0000)
layout:setRightMargin(29.0000)
layout:setTopMargin(-8.0000)
layout:setBottomMargin(-6.0000)
hall_room_fish_1_eyes_20:setBlendFunc({src = 1, dst = 771})
fish_eye:addChild(hall_room_fish_1_eyes_20)

--Create hall_room_fish_1_eyes_20_0
local hall_room_fish_1_eyes_20_0 = cc.Sprite:create("hall/room/hall_room_fish_1_eyes.png")
hall_room_fish_1_eyes_20_0:setName("hall_room_fish_1_eyes_20_0")
hall_room_fish_1_eyes_20_0:setTag(126)
hall_room_fish_1_eyes_20_0:setCascadeColorEnabled(true)
hall_room_fish_1_eyes_20_0:setCascadeOpacityEnabled(true)
hall_room_fish_1_eyes_20_0:setPosition(8.0000, 1.0000)
hall_room_fish_1_eyes_20_0:setScaleX(0.2000)
hall_room_fish_1_eyes_20_0:setScaleY(0.2000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_fish_1_eyes_20_0)
layout:setSize({width = 14.0000, height = 14.0000})
layout:setLeftMargin(1.0000)
layout:setRightMargin(-15.0000)
layout:setTopMargin(-8.0000)
layout:setBottomMargin(-6.0000)
hall_room_fish_1_eyes_20_0:setBlendFunc({src = 1, dst = 771})
fish_eye:addChild(hall_room_fish_1_eyes_20_0)

--Create hall_room_title_light_3_14_0
local hall_room_title_light_3_14_0 = cc.Sprite:create("hall/room/hall_room_title_light_3.png")
hall_room_title_light_3_14_0:setName("hall_room_title_light_3_14_0")
hall_room_title_light_3_14_0:setTag(134)
hall_room_title_light_3_14_0:setCascadeColorEnabled(true)
hall_room_title_light_3_14_0:setCascadeOpacityEnabled(true)
hall_room_title_light_3_14_0:setPosition(-136.3257, 145.6497)
hall_room_title_light_3_14_0:setScaleX(0.7500)
hall_room_title_light_3_14_0:setScaleY(0.7500)
hall_room_title_light_3_14_0:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_light_3_14_0)
layout:setSize({width = 50.0000, height = 50.0000})
layout:setLeftMargin(-161.3257)
layout:setRightMargin(111.3257)
layout:setTopMargin(-170.6497)
layout:setBottomMargin(120.6497)
hall_room_title_light_3_14_0:setBlendFunc({src = 774, dst = 1})
fish:addChild(hall_room_title_light_3_14_0)

--Create hall_room_bgdown_3_2_2
local hall_room_bgdown_3_2_2 = cc.Sprite:create("hall/room/hall_room_bgdown_3_2.png")
hall_room_bgdown_3_2_2:setName("hall_room_bgdown_3_2_2")
hall_room_bgdown_3_2_2:setTag(122)
hall_room_bgdown_3_2_2:setCascadeColorEnabled(true)
hall_room_bgdown_3_2_2:setCascadeOpacityEnabled(true)
hall_room_bgdown_3_2_2:setPosition(52.0000, -16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_bgdown_3_2_2)
layout:setSize({width = 114.0000, height = 106.0000})
layout:setLeftMargin(-5.0000)
layout:setRightMargin(-109.0000)
layout:setTopMargin(-37.0000)
layout:setBottomMargin(-69.0000)
hall_room_bgdown_3_2_2:setBlendFunc({src = 1, dst = 771})
Node:addChild(hall_room_bgdown_3_2_2)

--Create room_effect
local room_effect=cc.Node:create()
room_effect:setName("room_effect")
room_effect:setTag(76)
room_effect:setCascadeColorEnabled(true)
room_effect:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(room_effect)
Node:addChild(room_effect)

--Create hall_room_effect_3_1_6
local hall_room_effect_3_1_6 = cc.Sprite:create("hall/room/hall_room_effect_3_1.png")
hall_room_effect_3_1_6:setName("hall_room_effect_3_1_6")
hall_room_effect_3_1_6:setTag(127)
hall_room_effect_3_1_6:setCascadeColorEnabled(true)
hall_room_effect_3_1_6:setCascadeOpacityEnabled(true)
hall_room_effect_3_1_6:setPosition(139.2786, 11.3290)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_effect_3_1_6)
layout:setSize({width = 64.0000, height = 54.0000})
layout:setLeftMargin(107.2786)
layout:setRightMargin(-171.2786)
layout:setTopMargin(-38.3290)
layout:setBottomMargin(-15.6710)
hall_room_effect_3_1_6:setBlendFunc({src = 1, dst = 771})
room_effect:addChild(hall_room_effect_3_1_6)

--Create hall_room_effect_3_2_7
local hall_room_effect_3_2_7 = cc.Sprite:create("hall/room/hall_room_effect_3_2.png")
hall_room_effect_3_2_7:setName("hall_room_effect_3_2_7")
hall_room_effect_3_2_7:setTag(128)
hall_room_effect_3_2_7:setCascadeColorEnabled(true)
hall_room_effect_3_2_7:setCascadeOpacityEnabled(true)
hall_room_effect_3_2_7:setPosition(-137.8355, 22.5573)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_effect_3_2_7)
layout:setSize({width = 78.0000, height = 56.0000})
layout:setLeftMargin(-176.8355)
layout:setRightMargin(98.8355)
layout:setTopMargin(-50.5573)
layout:setBottomMargin(-5.4427)
hall_room_effect_3_2_7:setBlendFunc({src = 1, dst = 771})
room_effect:addChild(hall_room_effect_3_2_7)

--Create hall_room_effect_3_3_8
local hall_room_effect_3_3_8 = cc.Sprite:create("hall/room/hall_room_effect_3_3.png")
hall_room_effect_3_3_8:setName("hall_room_effect_3_3_8")
hall_room_effect_3_3_8:setTag(129)
hall_room_effect_3_3_8:setCascadeColorEnabled(true)
hall_room_effect_3_3_8:setCascadeOpacityEnabled(true)
hall_room_effect_3_3_8:setPosition(107.8356, 166.2282)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_effect_3_3_8)
layout:setSize({width = 74.0000, height = 56.0000})
layout:setLeftMargin(70.8356)
layout:setRightMargin(-144.8356)
layout:setTopMargin(-194.2282)
layout:setBottomMargin(138.2282)
hall_room_effect_3_3_8:setBlendFunc({src = 1, dst = 771})
room_effect:addChild(hall_room_effect_3_3_8)

--Create hall_room_effect_3_4_9
local hall_room_effect_3_4_9 = cc.Sprite:create("hall/room/hall_room_effect_3_4.png")
hall_room_effect_3_4_9:setName("hall_room_effect_3_4_9")
hall_room_effect_3_4_9:setTag(130)
hall_room_effect_3_4_9:setCascadeColorEnabled(true)
hall_room_effect_3_4_9:setCascadeOpacityEnabled(true)
hall_room_effect_3_4_9:setPosition(-141.3288, 106.3928)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_effect_3_4_9)
layout:setSize({width = 42.0000, height = 42.0000})
layout:setLeftMargin(-162.3288)
layout:setRightMargin(120.3288)
layout:setTopMargin(-127.3928)
layout:setBottomMargin(85.3928)
hall_room_effect_3_4_9:setBlendFunc({src = 1, dst = 771})
room_effect:addChild(hall_room_effect_3_4_9)

--Create hall_room_effect_3_5_10
local hall_room_effect_3_5_10 = cc.Sprite:create("hall/room/hall_room_effect_3_5.png")
hall_room_effect_3_5_10:setName("hall_room_effect_3_5_10")
hall_room_effect_3_5_10:setTag(131)
hall_room_effect_3_5_10:setCascadeColorEnabled(true)
hall_room_effect_3_5_10:setCascadeOpacityEnabled(true)
hall_room_effect_3_5_10:setPosition(140.2294, 111.6717)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_effect_3_5_10)
layout:setSize({width = 28.0000, height = 26.0000})
layout:setLeftMargin(126.2294)
layout:setRightMargin(-154.2294)
layout:setTopMargin(-124.6717)
layout:setBottomMargin(98.6717)
hall_room_effect_3_5_10:setBlendFunc({src = 1, dst = 771})
room_effect:addChild(hall_room_effect_3_5_10)

--Create title
local title=cc.Node:create()
title:setName("title")
title:setTag(80)
title:setCascadeColorEnabled(true)
title:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(title)
Node:addChild(title)

--Create hall_room_title_2_9
local hall_room_title_2_9 = cc.Sprite:create("hall/room/hall_room_title_3.png")
hall_room_title_2_9:setName("hall_room_title_2_9")
hall_room_title_2_9:setTag(79)
hall_room_title_2_9:setCascadeColorEnabled(true)
hall_room_title_2_9:setCascadeOpacityEnabled(true)
hall_room_title_2_9:setPosition(0.0000, -86.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_2_9)
layout:setSize({width = 278.0000, height = 100.0000})
layout:setLeftMargin(-139.0000)
layout:setRightMargin(-139.0000)
layout:setTopMargin(36.0000)
layout:setBottomMargin(-136.0000)
hall_room_title_2_9:setBlendFunc({src = 1, dst = 771})
title:addChild(hall_room_title_2_9)

--Create hall_room_title_light_3_14
local hall_room_title_light_3_14 = cc.Sprite:create("hall/room/hall_room_title_light_3.png")
hall_room_title_light_3_14:setName("hall_room_title_light_3_14")
hall_room_title_light_3_14:setTag(85)
hall_room_title_light_3_14:setCascadeColorEnabled(true)
hall_room_title_light_3_14:setCascadeOpacityEnabled(true)
hall_room_title_light_3_14:setPosition(128.4567, -43.3778)
hall_room_title_light_3_14:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_light_3_14)
layout:setSize({width = 50.0000, height = 50.0000})
layout:setLeftMargin(103.4567)
layout:setRightMargin(-153.4567)
layout:setTopMargin(18.3778)
layout:setBottomMargin(-68.3778)
hall_room_title_light_3_14:setBlendFunc({src = 1, dst = 1})
title:addChild(hall_room_title_light_3_14)

--Create run_light
local run_light = ccui.Layout:create()
run_light:ignoreContentAdaptWithSize(false)
run_light:setClippingEnabled(true)
run_light:setBackGroundColorOpacity(102)
run_light:setLayoutComponentEnabled(true)
run_light:setName("run_light")
run_light:setTag(86)
run_light:setCascadeColorEnabled(true)
run_light:setCascadeOpacityEnabled(true)
run_light:setPosition(-130.7661, -119.5507)
run_light:setScaleX(1.2800)
run_light:setScaleY(0.3025)
run_light:setRotationSkewX(5.9993)
run_light:setRotationSkewY(-4.0006)
layout = ccui.LayoutComponent:bindLayoutComponent(run_light)
layout:setSize({width = 200.0000, height = 200.0000})
layout:setLeftMargin(-130.7661)
layout:setRightMargin(-69.2339)
layout:setTopMargin(-80.4493)
layout:setBottomMargin(-119.5507)
title:addChild(run_light)

--Create hall_room_title_light_1_13
local hall_room_title_light_1_13 = cc.Sprite:create("hall/room/hall_room_title_light_1.png")
hall_room_title_light_1_13:setName("hall_room_title_light_1_13")
hall_room_title_light_1_13:setTag(84)
hall_room_title_light_1_13:setCascadeColorEnabled(true)
hall_room_title_light_1_13:setCascadeOpacityEnabled(true)
hall_room_title_light_1_13:setPosition(-32.4290, 97.2122)
hall_room_title_light_1_13:setScaleX(0.8000)
hall_room_title_light_1_13:setScaleY(2.4847)
hall_room_title_light_1_13:setRotationSkewX(-2.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_light_1_13)
layout:setPositionPercentX(-0.1621)
layout:setPositionPercentY(0.4861)
layout:setPercentWidth(0.4700)
layout:setPercentHeight(0.5200)
layout:setSize({width = 94.0000, height = 104.0000})
layout:setLeftMargin(-79.4290)
layout:setRightMargin(185.4290)
layout:setTopMargin(50.7878)
layout:setBottomMargin(45.2122)
hall_room_title_light_1_13:setBlendFunc({src = 774, dst = 1})
run_light:addChild(hall_room_title_light_1_13)

--Create hall_room_title_light_1_13_0
local hall_room_title_light_1_13_0 = cc.Sprite:create("hall/room/hall_room_title_light_1.png")
hall_room_title_light_1_13_0:setName("hall_room_title_light_1_13_0")
hall_room_title_light_1_13_0:setTag(96)
hall_room_title_light_1_13_0:setCascadeColorEnabled(true)
hall_room_title_light_1_13_0:setCascadeOpacityEnabled(true)
hall_room_title_light_1_13_0:setPosition(-32.4290, 97.2122)
hall_room_title_light_1_13_0:setScaleX(0.8000)
hall_room_title_light_1_13_0:setScaleY(2.4847)
hall_room_title_light_1_13_0:setRotationSkewX(-2.0000)
hall_room_title_light_1_13_0:setOpacity(127)
layout = ccui.LayoutComponent:bindLayoutComponent(hall_room_title_light_1_13_0)
layout:setPositionPercentX(-0.1621)
layout:setPositionPercentY(0.4861)
layout:setPercentWidth(0.4700)
layout:setPercentHeight(0.5200)
layout:setSize({width = 94.0000, height = 104.0000})
layout:setLeftMargin(-79.4290)
layout:setRightMargin(185.4290)
layout:setTopMargin(50.7878)
layout:setBottomMargin(45.2122)
hall_room_title_light_1_13_0:setBlendFunc({src = 774, dst = 1})
run_light:addChild(hall_room_title_light_1_13_0)

--Create node_unlocked
innerCSD = require("ui.hall.room.uiroom_unlocked")
innerProject = innerCSD.create(callBackProvider)
local node_unlocked = innerProject.root
node_unlocked.animation = innerProject.animation
node_unlocked:setName("node_unlocked")
node_unlocked:setTag(75)
node_unlocked:setCascadeColorEnabled(true)
node_unlocked:setCascadeOpacityEnabled(true)
node_unlocked:setPosition(85.0000, -145.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(node_unlocked)
layout:setLeftMargin(85.0000)
layout:setRightMargin(-85.0000)
layout:setTopMargin(145.0000)
layout:setBottomMargin(-145.0000)
innerProject.animation:setTimeSpeed(1.0000)
node_unlocked:runAction(innerProject.animation)
Node:addChild(node_unlocked)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(120)
result['animation']:setTimeSpeed(1.0000)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(light)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(light)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setX(0.0000)
localFrame:setY(5.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(bg)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(bg)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(bg)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0200)
localFrame:setScaleY(0.9500)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(110)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0167)
localFrame:setScaleY(0.9583)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0200)
localFrame:setScaleY(0.9500)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_fish_2_7)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(7.7800)
localFrame:setY(119.3200)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(7.7800)
localFrame:setY(119.3200)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(7.7800)
localFrame:setY(119.3200)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(fish_eye)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-136.3257)
localFrame:setY(145.6497)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(85)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-136.3257)
localFrame:setY(149.2571)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_title_light_3_14_0)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.7500)
localFrame:setScaleY(0.7500)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(85)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.7500)
localFrame:setScaleY(0.7500)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_title_light_3_14_0)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(85)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(360.0000)
localFrame:setSkewY(360.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_title_light_3_14_0)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(50)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(75)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(85)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(hall_room_title_light_3_14_0)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setX(0.0000)
localFrame:setY(10.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(1)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(fish)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(fish)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(52.0000)
localFrame:setY(-16.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setX(52.0000)
localFrame:setY(-11.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(52.0000)
localFrame:setY(-16.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_bgdown_3_2_2)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(139.2786)
localFrame:setY(11.3290)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(37)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(140.0000)
localFrame:setY(17.1008)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(61)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(140.0000)
localFrame:setY(19.9867)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(139.2786)
localFrame:setY(11.3290)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_effect_3_1_6)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-137.8355)
localFrame:setY(22.5573)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(81)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-138.5570)
localFrame:setY(32.6579)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-137.8355)
localFrame:setY(22.5573)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_effect_3_2_7)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(107.8356)
localFrame:setY(166.2282)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(51)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(110.7215)
localFrame:setY(183.5437)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(107.8356)
localFrame:setY(166.2282)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_effect_3_3_8)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-141.3288)
localFrame:setY(106.3928)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(88)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-140.6073)
localFrame:setY(96.2920)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-141.3288)
localFrame:setY(106.3928)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_effect_3_4_9)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(140.2294)
localFrame:setY(111.6717)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(73)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(127.9641)
localFrame:setY(103.7353)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(140.2294)
localFrame:setY(111.6717)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_effect_3_5_10)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(128.4567)
localFrame:setY(-43.3778)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(129.0602)
localFrame:setY(-45.1882)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_title_light_3_14)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(hall_room_title_light_3_14)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(520.0000)
localFrame:setSkewY(520.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(hall_room_title_light_3_14)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(35)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(55)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(80)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(90)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(hall_room_title_light_3_14)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(13)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-32.4290)
localFrame:setY(97.2122)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(40)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(232.1451)
localFrame:setY(90.7435)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_title_light_1_13)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(21)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(-32.4290)
localFrame:setY(97.2122)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(48)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(232.1451)
localFrame:setY(90.7435)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(hall_room_title_light_1_13_0)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(60)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(4.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(120)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(0.0000)
localFrame:setY(0.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(title)
--Create Animation List
local roomact = {name="roomact", startIndex=0, endIndex=120}
result['animation']:addAnimationInfo(roomact)
local stopact = {name="stopact", startIndex=0, endIndex=1}
result['animation']:addAnimationInfo(stopact)

result['root'] = Node
return result;
end

return Result

