--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorType(1)
panel:setBackGroundColor({r = 150, g = 200, b = 255})
panel:setBackGroundColorOpacity(0)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(140)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
Node:addChild(panel)

--Create image_bg
local image_bg = ccui.ImageView:create()
image_bg:ignoreContentAdaptWithSize(false)
image_bg:loadTexture("common/layerbg/com_bg_pic_3.png",0)
image_bg:setScale9Enabled(true)
image_bg:setCapInsets({x = 145, y = 92, width = 1, height = 1})
image_bg:setLayoutComponentEnabled(true)
image_bg:setName("image_bg")
image_bg:setTag(129)
image_bg:setCascadeColorEnabled(true)
image_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(image_bg)
layout:setSize({width = 663.0000, height = 416.0000})
layout:setLeftMargin(-331.5000)
layout:setRightMargin(-331.5000)
layout:setTopMargin(-208.0000)
layout:setBottomMargin(-208.0000)
panel:addChild(image_bg)

--Create img_bg_2
local img_bg_2 = ccui.ImageView:create()
img_bg_2:ignoreContentAdaptWithSize(false)
img_bg_2:loadTexture("common/layerbg/com_bg_pic_bsbg.png",0)
img_bg_2:setScale9Enabled(true)
img_bg_2:setCapInsets({x = 37, y = 36, width = 1, height = 1})
img_bg_2:setLayoutComponentEnabled(true)
img_bg_2:setName("img_bg_2")
img_bg_2:setTag(130)
img_bg_2:setCascadeColorEnabled(true)
img_bg_2:setCascadeOpacityEnabled(true)
img_bg_2:setPosition(331.5002, 181.5175)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg_2)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4363)
layout:setPercentWidth(0.9472)
layout:setPercentHeight(0.7933)
layout:setSize({width = 628.0000, height = 330.0000})
layout:setLeftMargin(17.5002)
layout:setRightMargin(17.4998)
layout:setTopMargin(69.4825)
layout:setBottomMargin(16.5175)
image_bg:addChild(img_bg_2)

--Create spr_title
local spr_title = cc.Sprite:create("common/set/set_pic_yx.png")
spr_title:setName("spr_title")
spr_title:setTag(132)
spr_title:setCascadeColorEnabled(true)
spr_title:setCascadeOpacityEnabled(true)
spr_title:setPosition(0.0000, 163.4979)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_title)
layout:setPositionPercentXEnabled(true)
layout:setSize({width = 88.0000, height = 42.0000})
layout:setLeftMargin(-44.0000)
layout:setRightMargin(-44.0000)
layout:setTopMargin(-184.4979)
layout:setBottomMargin(142.4979)
spr_title:setBlendFunc({src = 1, dst = 771})
panel:addChild(spr_title)

--Create btn_close
local btn_close = ccui.Button:create()
btn_close:ignoreContentAdaptWithSize(false)
btn_close:loadTextureNormal("common/btn/com_btn_close_0.png",0)
btn_close:loadTexturePressed("common/btn/com_btn_close_1.png",0)
btn_close:loadTextureDisabled("common/btn/com_btn_close_1.png",0)
btn_close:setTitleFontSize(14)
btn_close:setTitleColor({r = 65, g = 65, b = 70})
btn_close:setScale9Enabled(true)
btn_close:setCapInsets({x = 15, y = 11, width = 40, height = 48})
btn_close:setLayoutComponentEnabled(true)
btn_close:setName("btn_close")
btn_close:setTag(133)
btn_close:setCascadeColorEnabled(true)
btn_close:setCascadeOpacityEnabled(true)
btn_close:setPosition(298.9856, 174.0309)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_close)
layout:setSize({width = 70.0000, height = 70.0000})
layout:setLeftMargin(263.9856)
layout:setRightMargin(-333.9856)
layout:setTopMargin(-209.0309)
layout:setBottomMargin(139.0309)
panel:addChild(btn_close)

--Create image_effectbg
local image_effectbg = ccui.ImageView:create()
image_effectbg:ignoreContentAdaptWithSize(false)
image_effectbg:loadTexture("common/set/set_bar_bg.png",0)
image_effectbg:setScale9Enabled(true)
image_effectbg:setCapInsets({x = 23, y = 0, width = 1, height = 36})
image_effectbg:setLayoutComponentEnabled(true)
image_effectbg:setName("image_effectbg")
image_effectbg:setTag(138)
image_effectbg:setCascadeColorEnabled(true)
image_effectbg:setCascadeOpacityEnabled(true)
image_effectbg:setPosition(78.4132, -78.0562)
layout = ccui.LayoutComponent:bindLayoutComponent(image_effectbg)
layout:setSize({width = 350.0000, height = 40.0000})
layout:setLeftMargin(-96.5868)
layout:setRightMargin(-253.4132)
layout:setTopMargin(58.0562)
layout:setBottomMargin(-98.0562)
panel:addChild(image_effectbg)

--Create slider_effect
local slider_effect = ccui.Slider:create()
slider_effect:ignoreContentAdaptWithSize(false)
slider_effect:loadProgressBarTexture("common/set/set_bar_blood.png",0)
slider_effect:loadSlidBallTextureNormal("common/set/set_btn.png",0)
slider_effect:loadSlidBallTexturePressed("common/set/set_btn.png",0)
slider_effect:loadSlidBallTextureDisabled("common/set/set_btn.png",0)
slider_effect:setPercent(43)
slider_effect:setLayoutComponentEnabled(true)
slider_effect:setName("slider_effect")
slider_effect:setTag(139)
slider_effect:setCascadeColorEnabled(true)
slider_effect:setCascadeOpacityEnabled(true)
slider_effect:setPosition(78.4128, -78.0561)
layout = ccui.LayoutComponent:bindLayoutComponent(slider_effect)
layout:setSize({width = 346.0000, height = 36.0000})
layout:setLeftMargin(-94.5872)
layout:setRightMargin(-251.4128)
layout:setTopMargin(60.0561)
layout:setBottomMargin(-96.0561)
panel:addChild(slider_effect)

--Create spe_word_yxyx
local spe_word_yxyx = cc.Sprite:create("common/set/set_pic_yxyx.png")
spe_word_yxyx:setName("spe_word_yxyx")
spe_word_yxyx:setTag(137)
spe_word_yxyx:setCascadeColorEnabled(true)
spe_word_yxyx:setCascadeOpacityEnabled(true)
spe_word_yxyx:setPosition(-185.6106, -78.7992)
layout = ccui.LayoutComponent:bindLayoutComponent(spe_word_yxyx)
layout:setSize({width = 166.0000, height = 38.0000})
layout:setLeftMargin(-268.6106)
layout:setRightMargin(102.6106)
layout:setTopMargin(59.7992)
layout:setBottomMargin(-97.7992)
spe_word_yxyx:setBlendFunc({src = 1, dst = 771})
panel:addChild(spe_word_yxyx)

--Create image_musicbg
local image_musicbg = ccui.ImageView:create()
image_musicbg:ignoreContentAdaptWithSize(false)
image_musicbg:loadTexture("common/set/set_bar_bg.png",0)
image_musicbg:setScale9Enabled(true)
image_musicbg:setCapInsets({x = 23, y = 0, width = 1, height = 36})
image_musicbg:setLayoutComponentEnabled(true)
image_musicbg:setName("image_musicbg")
image_musicbg:setTag(135)
image_musicbg:setCascadeColorEnabled(true)
image_musicbg:setCascadeOpacityEnabled(true)
image_musicbg:setPosition(80.4137, 41.9430)
layout = ccui.LayoutComponent:bindLayoutComponent(image_musicbg)
layout:setSize({width = 350.0000, height = 40.0000})
layout:setLeftMargin(-94.5863)
layout:setRightMargin(-255.4137)
layout:setTopMargin(-61.9430)
layout:setBottomMargin(21.9430)
panel:addChild(image_musicbg)

--Create slider_music
local slider_music = ccui.Slider:create()
slider_music:ignoreContentAdaptWithSize(false)
slider_music:loadProgressBarTexture("common/set/set_bar_blood.png",0)
slider_music:loadSlidBallTextureNormal("common/set/set_btn.png",0)
slider_music:loadSlidBallTexturePressed("common/set/set_btn.png",0)
slider_music:loadSlidBallTextureDisabled("common/set/set_btn.png",0)
slider_music:setPercent(40)
slider_music:setLayoutComponentEnabled(true)
slider_music:setName("slider_music")
slider_music:setTag(136)
slider_music:setCascadeColorEnabled(true)
slider_music:setCascadeOpacityEnabled(true)
slider_music:setPosition(80.4135, 41.9436)
layout = ccui.LayoutComponent:bindLayoutComponent(slider_music)
layout:setSize({width = 346.0000, height = 36.0000})
layout:setLeftMargin(-92.5865)
layout:setRightMargin(-253.4135)
layout:setTopMargin(-59.9436)
layout:setBottomMargin(23.9436)
panel:addChild(slider_music)

--Create spe_word_bjyy
local spe_word_bjyy = cc.Sprite:create("common/set/set_pic_bjyy.png")
spe_word_bjyy:setName("spe_word_bjyy")
spe_word_bjyy:setTag(134)
spe_word_bjyy:setCascadeColorEnabled(true)
spe_word_bjyy:setCascadeOpacityEnabled(true)
spe_word_bjyy:setPosition(-185.7704, 39.2780)
layout = ccui.LayoutComponent:bindLayoutComponent(spe_word_bjyy)
layout:setSize({width = 166.0000, height = 38.0000})
layout:setLeftMargin(-268.7704)
layout:setRightMargin(102.7704)
layout:setTopMargin(-58.2780)
layout:setBottomMargin(20.2780)
spe_word_bjyy:setBlendFunc({src = 1, dst = 771})
panel:addChild(spe_word_bjyy)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

