--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create image_bg
local image_bg = ccui.ImageView:create()
image_bg:ignoreContentAdaptWithSize(false)
image_bg:loadTexture("common/layerbg/com_pic_infobg.png",0)
image_bg:setScale9Enabled(true)
image_bg:setCapInsets({x = 42, y = 26, width = 1, height = 1})
image_bg:setLayoutComponentEnabled(true)
image_bg:setName("image_bg")
image_bg:setTag(3206)
image_bg:setCascadeColorEnabled(true)
image_bg:setCascadeOpacityEnabled(true)
image_bg:setPosition(0.0000, 142.6048)
image_bg:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(image_bg)
layout:setSize({width = 400.0000, height = 52.0000})
layout:setLeftMargin(-200.0000)
layout:setRightMargin(-200.0000)
layout:setTopMargin(-168.6048)
layout:setBottomMargin(116.6048)
Node:addChild(image_bg)

--Create fnt_coin
local fnt_coin = ccui.TextBMFont:create()
fnt_coin:setFntFile("fnt/bonus_num_1.fnt")
fnt_coin:setString([[15000]])
fnt_coin:setLayoutComponentEnabled(true)
fnt_coin:setName("fnt_coin")
fnt_coin:setTag(3207)
fnt_coin:setCascadeColorEnabled(true)
fnt_coin:setCascadeOpacityEnabled(true)
fnt_coin:setAnchorPoint(0.0000, 0.5000)
fnt_coin:setPosition(200.0000, 26.0000)
fnt_coin:setScaleX(0.5000)
fnt_coin:setScaleY(0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(fnt_coin)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5000)
layout:setPercentHeight(0.9231)
layout:setSize({width = 200.0000, height = 48.0000})
layout:setLeftMargin(200.0000)
layout:setTopMargin(2.0000)
layout:setBottomMargin(2.0000)
image_bg:addChild(fnt_coin)

--Create text_word_2
local text_word_2 = ccui.Text:create()
text_word_2:ignoreContentAdaptWithSize(true)
text_word_2:setTextAreaSize({width = 0, height = 0})
text_word_2:setFontSize(52)
text_word_2:setString([[鱼币]])
text_word_2:setLayoutComponentEnabled(true)
text_word_2:setName("text_word_2")
text_word_2:setTag(3210)
text_word_2:setCascadeColorEnabled(true)
text_word_2:setCascadeOpacityEnabled(true)
text_word_2:setAnchorPoint(0.0000, 0.5000)
text_word_2:setPosition(200.0000, 24.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(text_word_2)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(1.0000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5200)
layout:setPercentHeight(1.0833)
layout:setSize({width = 104.0000, height = 52.0000})
layout:setLeftMargin(200.0000)
layout:setRightMargin(-104.0000)
layout:setTopMargin(-2.0000)
layout:setBottomMargin(-2.0000)
fnt_coin:addChild(text_word_2)

--Create text_word_1
local text_word_1 = ccui.Text:create()
text_word_1:ignoreContentAdaptWithSize(true)
text_word_1:setTextAreaSize({width = 0, height = 0})
text_word_1:setFontSize(52)
text_word_1:setString([[解锁炮倍赠]])
text_word_1:setLayoutComponentEnabled(true)
text_word_1:setName("text_word_1")
text_word_1:setTag(3209)
text_word_1:setCascadeColorEnabled(true)
text_word_1:setCascadeOpacityEnabled(true)
text_word_1:setAnchorPoint(1.0000, 0.5000)
text_word_1:setPosition(0.0000, 24.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(text_word_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.3000)
layout:setPercentHeight(1.0833)
layout:setSize({width = 260.0000, height = 52.0000})
layout:setLeftMargin(-260.0000)
layout:setRightMargin(200.0000)
layout:setTopMargin(-2.0000)
layout:setBottomMargin(-2.0000)
fnt_coin:addChild(text_word_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(50)
result['animation']:setTimeSpeed(0.4167)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(2)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.2000)
localFrame:setScaleY(1.2000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(4)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(46)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(48)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.2000)
localFrame:setScaleY(1.2000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(50)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(image_bg)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(4)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(46)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(50)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(image_bg)
--Create Animation List
local gunupgrade = {name="gunupgrade", startIndex=0, endIndex=54}
result['animation']:addAnimationInfo(gunupgrade)

result['root'] = Node
return result;
end

return Result

