--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create fnt_count
local fnt_count = ccui.TextBMFont:create()
fnt_count:setFntFile("fnt/dial_num.fnt")
fnt_count:setString([[12]])
fnt_count:setLayoutComponentEnabled(true)
fnt_count:setName("fnt_count")
fnt_count:setTag(18)
fnt_count:setCascadeColorEnabled(true)
fnt_count:setCascadeOpacityEnabled(true)
fnt_count:setPosition(0.0000, 211.8159)
layout = ccui.LayoutComponent:bindLayoutComponent(fnt_count)
layout:setSize({width = 58.0000, height = 34.0000})
layout:setLeftMargin(-29.0000)
layout:setRightMargin(-29.0000)
layout:setTopMargin(-228.8159)
layout:setBottomMargin(194.8159)
Node:addChild(fnt_count)

--Create spr_prop
local spr_prop = cc.Sprite:create("common/prop/prop_002.png")
spr_prop:setName("spr_prop")
spr_prop:setTag(19)
spr_prop:setCascadeColorEnabled(true)
spr_prop:setCascadeOpacityEnabled(true)
spr_prop:setPosition(0.0001, 150.8704)
spr_prop:setScaleX(0.8000)
spr_prop:setScaleY(0.8000)
layout = ccui.LayoutComponent:bindLayoutComponent(spr_prop)
layout:setSize({width = 112.0000, height = 112.0000})
layout:setLeftMargin(-55.9999)
layout:setRightMargin(-56.0001)
layout:setTopMargin(-206.8704)
layout:setBottomMargin(94.8704)
spr_prop:setBlendFunc({src = 1, dst = 771})
Node:addChild(spr_prop)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

