--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create light_1
local light_1 = cc.Sprite:create("common/com_changecannon.png")
light_1:setName("light_1")
light_1:setTag(406)
light_1:setCascadeColorEnabled(true)
light_1:setCascadeOpacityEnabled(true)
light_1:setScaleX(0.0010)
light_1:setScaleY(0.0010)
light_1:setColor({r = 255, g = 165, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(light_1)
layout:setSize({width = 144.0000, height = 148.0000})
layout:setLeftMargin(-72.0000)
layout:setRightMargin(-72.0000)
layout:setTopMargin(-74.0000)
layout:setBottomMargin(-74.0000)
light_1:setBlendFunc({src = 770, dst = 1})
Node:addChild(light_1)

--Create light_2
local light_2 = cc.Sprite:create("common/com_pic_light.png")
light_2:setName("light_2")
light_2:setTag(412)
light_2:setCascadeColorEnabled(true)
light_2:setCascadeOpacityEnabled(true)
light_2:setScaleX(0.0010)
light_2:setScaleY(0.0010)
layout = ccui.LayoutComponent:bindLayoutComponent(light_2)
layout:setSize({width = 106.0000, height = 106.0000})
layout:setLeftMargin(-53.0000)
layout:setRightMargin(-53.0000)
layout:setTopMargin(-53.0000)
layout:setBottomMargin(-53.0000)
light_2:setBlendFunc({src = 770, dst = 1})
Node:addChild(light_2)

--Create light_3
local light_3 = cc.Sprite:create("battle/effect/light_sd_2.png")
light_3:setName("light_3")
light_3:setTag(60)
light_3:setCascadeColorEnabled(true)
light_3:setCascadeOpacityEnabled(true)
light_3:setPosition(0.0000, -10.0000)
light_3:setScaleX(10.0000)
light_3:setScaleY(10.0000)
light_3:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(light_3)
layout:setSize({width = 32.0000, height = 32.0000})
layout:setLeftMargin(-16.0000)
layout:setRightMargin(-16.0000)
layout:setTopMargin(-6.0000)
layout:setBottomMargin(-26.0000)
light_3:setBlendFunc({src = 770, dst = 1})
Node:addChild(light_3)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(55)
result['animation']:setTimeSpeed(1.0000)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.0010)
localFrame:setScaleY(0.0010)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(2.5000)
localFrame:setScaleY(2.5000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(5.0000)
localFrame:setScaleY(5.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(light_1)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(5)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(light_1)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(0.0010)
localFrame:setScaleY(0.0010)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(15)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(2.3000)
localFrame:setScaleY(2.3000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(3.0000)
localFrame:setScaleY(3.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(light_2)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(10)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(15)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(153)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(light_2)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(10.0000)
localFrame:setScaleY(10.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(55)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setScaleX(20.0000)
localFrame:setScaleY(20.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(light_3)

--Create AlphaTimeline
local AlphaTimeline = ccs.Timeline:create()

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(0)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(5)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(255)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(30)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setAlpha(204)
AlphaTimeline:addFrame(localFrame)

localFrame = ccs.AlphaFrame:create()
localFrame:setFrameIndex(55)
localFrame:setTween(true)
localFrame:setTweenType(2)
localFrame:setAlpha(0)
AlphaTimeline:addFrame(localFrame)

result['animation']:addTimeline(AlphaTimeline)
AlphaTimeline:setNode(light_3)

--Create FrameEventTimeline
local FrameEventTimeline = ccs.Timeline:create()

localFrame = ccs.EventFrame:create()
localFrame:setFrameIndex(55)
localFrame:setTween(false)
localFrame:setEvent("end")
FrameEventTimeline:addFrame(localFrame)

result['animation']:addTimeline(FrameEventTimeline)
FrameEventTimeline:setNode(light_3)
--Create Animation List
local open = {name="open", startIndex=0, endIndex=55}
result['animation']:addAnimationInfo(open)
local beginkb = {name="beginkb", startIndex=0, endIndex=55}
result['animation']:addAnimationInfo(beginkb)

result['root'] = Node
return result;
end

return Result

